-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dct_Loop_Xpose_Row_Outer_Loop_proc is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    col_inbuf_i_7_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    col_inbuf_i_7_ce0 : OUT STD_LOGIC;
    col_inbuf_i_7_we0 : OUT STD_LOGIC;
    col_inbuf_i_7_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    col_inbuf_i_6_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    col_inbuf_i_6_ce0 : OUT STD_LOGIC;
    col_inbuf_i_6_we0 : OUT STD_LOGIC;
    col_inbuf_i_6_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    col_inbuf_i_5_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    col_inbuf_i_5_ce0 : OUT STD_LOGIC;
    col_inbuf_i_5_we0 : OUT STD_LOGIC;
    col_inbuf_i_5_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    col_inbuf_i_4_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    col_inbuf_i_4_ce0 : OUT STD_LOGIC;
    col_inbuf_i_4_we0 : OUT STD_LOGIC;
    col_inbuf_i_4_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    col_inbuf_i_3_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    col_inbuf_i_3_ce0 : OUT STD_LOGIC;
    col_inbuf_i_3_we0 : OUT STD_LOGIC;
    col_inbuf_i_3_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    col_inbuf_i_2_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    col_inbuf_i_2_ce0 : OUT STD_LOGIC;
    col_inbuf_i_2_we0 : OUT STD_LOGIC;
    col_inbuf_i_2_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    col_inbuf_i_1_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    col_inbuf_i_1_ce0 : OUT STD_LOGIC;
    col_inbuf_i_1_we0 : OUT STD_LOGIC;
    col_inbuf_i_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    col_inbuf_i_0_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    col_inbuf_i_0_ce0 : OUT STD_LOGIC;
    col_inbuf_i_0_we0 : OUT STD_LOGIC;
    col_inbuf_i_0_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    row_outbuf_i_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    row_outbuf_i_ce0 : OUT STD_LOGIC;
    row_outbuf_i_q0 : IN STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of dct_Loop_Xpose_Row_Outer_Loop_proc is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv6_3F : STD_LOGIC_VECTOR (5 downto 0) := "111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln66_fu_283_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_condition_exit_pp0_iter0_stage0_pp0_iter1_reg : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_loop_exit_ready_delayed : STD_LOGIC;
    signal trunc_ln66_fu_253_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln66_reg_357 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln66_reg_357_pp0_iter1_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal j_fu_257_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal j_reg_362 : STD_LOGIC_VECTOR (3 downto 0);
    signal j_reg_362_pp0_iter1_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln69_fu_277_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln69_reg_368 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_reg_373 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_icmp_ln694_phi_fu_208_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln72_fu_320_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln66_fu_325_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal indvar_flatten1_fu_68 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal add_ln66_1_fu_265_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_sig_allocacmp_indvar_flatten1_load : STD_LOGIC_VECTOR (5 downto 0);
    signal j2_fu_72 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal ap_sig_allocacmp_j2_load : STD_LOGIC_VECTOR (3 downto 0);
    signal i3_fu_76 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal i_fu_271_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_i3_load : STD_LOGIC_VECTOR (3 downto 0);
    signal row_outbuf_i_ce0_local : STD_LOGIC;
    signal col_inbuf_i_6_we0_local : STD_LOGIC;
    signal col_inbuf_i_6_ce0_local : STD_LOGIC;
    signal col_inbuf_i_5_we0_local : STD_LOGIC;
    signal col_inbuf_i_5_ce0_local : STD_LOGIC;
    signal col_inbuf_i_4_we0_local : STD_LOGIC;
    signal col_inbuf_i_4_ce0_local : STD_LOGIC;
    signal col_inbuf_i_3_we0_local : STD_LOGIC;
    signal col_inbuf_i_3_ce0_local : STD_LOGIC;
    signal col_inbuf_i_2_we0_local : STD_LOGIC;
    signal col_inbuf_i_2_ce0_local : STD_LOGIC;
    signal col_inbuf_i_1_we0_local : STD_LOGIC;
    signal col_inbuf_i_1_ce0_local : STD_LOGIC;
    signal col_inbuf_i_0_we0_local : STD_LOGIC;
    signal col_inbuf_i_0_ce0_local : STD_LOGIC;
    signal col_inbuf_i_7_we0_local : STD_LOGIC;
    signal col_inbuf_i_7_ce0_local : STD_LOGIC;
    signal select_ln57_fu_245_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln66_fu_239_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_307_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln66_cast_fu_304_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln72_fu_314_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_364 : BOOLEAN;
    signal ap_condition_137 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component dct_flow_control_loop_delay_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_loop_exit_ready_delayed : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_delay_pipe_U : component dct_flow_control_loop_delay_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_continue,
        ap_loop_exit_ready_delayed => ap_loop_exit_ready_delayed);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter2_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_0))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
            end if; 
        end if;
    end process;

    i3_fu_76_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_137)) then
                i3_fu_76 <= i_fu_271_p2;
            end if;
        end if;
    end process;

    indvar_flatten1_fu_68_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_137)) then
                indvar_flatten1_fu_68 <= add_ln66_1_fu_265_p2;
            end if;
        end if;
    end process;

    j2_fu_72_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_137)) then
                j2_fu_72 <= j_fu_257_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_condition_exit_pp0_iter0_stage0_pp0_iter1_reg <= ap_condition_exit_pp0_iter0_stage0;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                icmp_ln66_reg_373 <= icmp_ln66_fu_283_p2;
                j_reg_362 <= j_fu_257_p3;
                j_reg_362_pp0_iter1_reg <= j_reg_362;
                trunc_ln66_reg_357 <= trunc_ln66_fu_253_p1;
                trunc_ln66_reg_357_pp0_iter1_reg <= trunc_ln66_reg_357;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln69_reg_368 <= icmp_ln69_fu_277_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln66_1_fu_265_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten1_load) + unsigned(ap_const_lv6_1));
    add_ln66_fu_239_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_j2_load) + unsigned(ap_const_lv4_1));
    add_ln72_fu_314_p2 <= std_logic_vector(unsigned(tmp_fu_307_p3) + unsigned(select_ln66_cast_fu_304_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_start_int)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_start_int)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_done_reg = ap_const_logic_1);
    end process;


    ap_condition_137_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
                ap_condition_137 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_364_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln66_reg_373, ap_block_pp0_stage0)
    begin
                ap_condition_364 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln66_reg_373 = ap_const_lv1_0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, icmp_ln66_fu_283_p2, ap_start_int)
    begin
        if (((icmp_ln66_fu_283_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_done_reg, ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_loop_exit_ready_delayed_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_condition_exit_pp0_iter0_stage0_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0_pp0_iter1_reg) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_loop_exit_ready_delayed <= ap_const_logic_1;
        else 
            ap_loop_exit_ready_delayed <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_icmp_ln694_phi_fu_208_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln69_reg_368, ap_loop_init, ap_condition_364)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
            if ((ap_const_boolean_1 = ap_condition_364)) then 
                ap_phi_mux_icmp_ln694_phi_fu_208_p4 <= icmp_ln69_reg_368;
            elsif ((ap_loop_init = ap_const_logic_1)) then 
                ap_phi_mux_icmp_ln694_phi_fu_208_p4 <= ap_const_lv1_0;
            else 
                ap_phi_mux_icmp_ln694_phi_fu_208_p4 <= icmp_ln69_reg_368;
            end if;
        else 
            ap_phi_mux_icmp_ln694_phi_fu_208_p4 <= icmp_ln69_reg_368;
        end if; 
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i3_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, ap_block_pp0_stage0, i3_fu_76, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i3_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_i3_load <= i3_fu_76;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten1_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, ap_block_pp0_stage0, indvar_flatten1_fu_68, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten1_load <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_indvar_flatten1_load <= indvar_flatten1_fu_68;
        end if; 
    end process;


    ap_sig_allocacmp_j2_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, ap_block_pp0_stage0, j2_fu_72, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_j2_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_j2_load <= j2_fu_72;
        end if; 
    end process;

    col_inbuf_i_0_address0 <= zext_ln66_fu_325_p1(3 - 1 downto 0);
    col_inbuf_i_0_ce0 <= col_inbuf_i_0_ce0_local;

    col_inbuf_i_0_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            col_inbuf_i_0_ce0_local <= ap_const_logic_1;
        else 
            col_inbuf_i_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    col_inbuf_i_0_d0 <= row_outbuf_i_q0;
    col_inbuf_i_0_we0 <= col_inbuf_i_0_we0_local;

    col_inbuf_i_0_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln66_reg_357_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln66_reg_357_pp0_iter1_reg = ap_const_lv3_0))) then 
            col_inbuf_i_0_we0_local <= ap_const_logic_1;
        else 
            col_inbuf_i_0_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    col_inbuf_i_1_address0 <= zext_ln66_fu_325_p1(3 - 1 downto 0);
    col_inbuf_i_1_ce0 <= col_inbuf_i_1_ce0_local;

    col_inbuf_i_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            col_inbuf_i_1_ce0_local <= ap_const_logic_1;
        else 
            col_inbuf_i_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    col_inbuf_i_1_d0 <= row_outbuf_i_q0;
    col_inbuf_i_1_we0 <= col_inbuf_i_1_we0_local;

    col_inbuf_i_1_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln66_reg_357_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln66_reg_357_pp0_iter1_reg = ap_const_lv3_1))) then 
            col_inbuf_i_1_we0_local <= ap_const_logic_1;
        else 
            col_inbuf_i_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    col_inbuf_i_2_address0 <= zext_ln66_fu_325_p1(3 - 1 downto 0);
    col_inbuf_i_2_ce0 <= col_inbuf_i_2_ce0_local;

    col_inbuf_i_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            col_inbuf_i_2_ce0_local <= ap_const_logic_1;
        else 
            col_inbuf_i_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    col_inbuf_i_2_d0 <= row_outbuf_i_q0;
    col_inbuf_i_2_we0 <= col_inbuf_i_2_we0_local;

    col_inbuf_i_2_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln66_reg_357_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln66_reg_357_pp0_iter1_reg = ap_const_lv3_2))) then 
            col_inbuf_i_2_we0_local <= ap_const_logic_1;
        else 
            col_inbuf_i_2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    col_inbuf_i_3_address0 <= zext_ln66_fu_325_p1(3 - 1 downto 0);
    col_inbuf_i_3_ce0 <= col_inbuf_i_3_ce0_local;

    col_inbuf_i_3_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            col_inbuf_i_3_ce0_local <= ap_const_logic_1;
        else 
            col_inbuf_i_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    col_inbuf_i_3_d0 <= row_outbuf_i_q0;
    col_inbuf_i_3_we0 <= col_inbuf_i_3_we0_local;

    col_inbuf_i_3_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln66_reg_357_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln66_reg_357_pp0_iter1_reg = ap_const_lv3_3))) then 
            col_inbuf_i_3_we0_local <= ap_const_logic_1;
        else 
            col_inbuf_i_3_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    col_inbuf_i_4_address0 <= zext_ln66_fu_325_p1(3 - 1 downto 0);
    col_inbuf_i_4_ce0 <= col_inbuf_i_4_ce0_local;

    col_inbuf_i_4_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            col_inbuf_i_4_ce0_local <= ap_const_logic_1;
        else 
            col_inbuf_i_4_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    col_inbuf_i_4_d0 <= row_outbuf_i_q0;
    col_inbuf_i_4_we0 <= col_inbuf_i_4_we0_local;

    col_inbuf_i_4_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln66_reg_357_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln66_reg_357_pp0_iter1_reg = ap_const_lv3_4))) then 
            col_inbuf_i_4_we0_local <= ap_const_logic_1;
        else 
            col_inbuf_i_4_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    col_inbuf_i_5_address0 <= zext_ln66_fu_325_p1(3 - 1 downto 0);
    col_inbuf_i_5_ce0 <= col_inbuf_i_5_ce0_local;

    col_inbuf_i_5_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            col_inbuf_i_5_ce0_local <= ap_const_logic_1;
        else 
            col_inbuf_i_5_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    col_inbuf_i_5_d0 <= row_outbuf_i_q0;
    col_inbuf_i_5_we0 <= col_inbuf_i_5_we0_local;

    col_inbuf_i_5_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln66_reg_357_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln66_reg_357_pp0_iter1_reg = ap_const_lv3_5))) then 
            col_inbuf_i_5_we0_local <= ap_const_logic_1;
        else 
            col_inbuf_i_5_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    col_inbuf_i_6_address0 <= zext_ln66_fu_325_p1(3 - 1 downto 0);
    col_inbuf_i_6_ce0 <= col_inbuf_i_6_ce0_local;

    col_inbuf_i_6_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            col_inbuf_i_6_ce0_local <= ap_const_logic_1;
        else 
            col_inbuf_i_6_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    col_inbuf_i_6_d0 <= row_outbuf_i_q0;
    col_inbuf_i_6_we0 <= col_inbuf_i_6_we0_local;

    col_inbuf_i_6_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln66_reg_357_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln66_reg_357_pp0_iter1_reg = ap_const_lv3_6))) then 
            col_inbuf_i_6_we0_local <= ap_const_logic_1;
        else 
            col_inbuf_i_6_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    col_inbuf_i_7_address0 <= zext_ln66_fu_325_p1(3 - 1 downto 0);
    col_inbuf_i_7_ce0 <= col_inbuf_i_7_ce0_local;

    col_inbuf_i_7_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            col_inbuf_i_7_ce0_local <= ap_const_logic_1;
        else 
            col_inbuf_i_7_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    col_inbuf_i_7_d0 <= row_outbuf_i_q0;
    col_inbuf_i_7_we0 <= col_inbuf_i_7_we0_local;

    col_inbuf_i_7_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln66_reg_357_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln66_reg_357_pp0_iter1_reg = ap_const_lv3_7))) then 
            col_inbuf_i_7_we0_local <= ap_const_logic_1;
        else 
            col_inbuf_i_7_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    i_fu_271_p2 <= std_logic_vector(unsigned(select_ln57_fu_245_p3) + unsigned(ap_const_lv4_1));
    icmp_ln66_fu_283_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten1_load = ap_const_lv6_3F) else "0";
    icmp_ln69_fu_277_p2 <= "1" when (i_fu_271_p2 = ap_const_lv4_8) else "0";
    j_fu_257_p3 <= 
        add_ln66_fu_239_p2 when (ap_phi_mux_icmp_ln694_phi_fu_208_p4(0) = '1') else 
        ap_sig_allocacmp_j2_load;
    row_outbuf_i_address0 <= zext_ln72_fu_320_p1(6 - 1 downto 0);
    row_outbuf_i_ce0 <= row_outbuf_i_ce0_local;

    row_outbuf_i_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            row_outbuf_i_ce0_local <= ap_const_logic_1;
        else 
            row_outbuf_i_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln57_fu_245_p3 <= 
        ap_const_lv4_0 when (ap_phi_mux_icmp_ln694_phi_fu_208_p4(0) = '1') else 
        ap_sig_allocacmp_i3_load;
    select_ln66_cast_fu_304_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_reg_362),6));
    tmp_fu_307_p3 <= (trunc_ln66_reg_357 & ap_const_lv3_0);
    trunc_ln66_fu_253_p1 <= select_ln57_fu_245_p3(3 - 1 downto 0);
    zext_ln66_fu_325_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_reg_362_pp0_iter1_reg),64));
    zext_ln72_fu_320_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln72_fu_314_p2),64));
end behav;
