-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dct_dct_1d_Pipeline_DCT_Outer_Loop is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    zext_ln46_1 : IN STD_LOGIC_VECTOR (5 downto 0);
    dst_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    dst_ce0 : OUT STD_LOGIC;
    dst_we0 : OUT STD_LOGIC;
    dst_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    sext_ln46_1 : IN STD_LOGIC_VECTOR (15 downto 0);
    sext_ln46_7 : IN STD_LOGIC_VECTOR (15 downto 0);
    sext_ln46 : IN STD_LOGIC_VECTOR (15 downto 0);
    sext_ln46_6 : IN STD_LOGIC_VECTOR (15 downto 0);
    sext_ln46_4 : IN STD_LOGIC_VECTOR (15 downto 0);
    sext_ln46_3 : IN STD_LOGIC_VECTOR (15 downto 0);
    sext_ln46_2 : IN STD_LOGIC_VECTOR (15 downto 0);
    sext_ln46_5 : IN STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of dct_dct_1d_Pipeline_DCT_Outer_Loop is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant ap_const_lv29_1000 : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000001000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln39_fu_289_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal dct_1d_dct_coeff_table_0_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal dct_1d_dct_coeff_table_0_q0 : STD_LOGIC_VECTOR (13 downto 0);
    signal dct_1d_dct_coeff_table_1_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal dct_1d_dct_coeff_table_1_q0 : STD_LOGIC_VECTOR (14 downto 0);
    signal dct_1d_dct_coeff_table_2_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal dct_1d_dct_coeff_table_2_q0 : STD_LOGIC_VECTOR (14 downto 0);
    signal dct_1d_dct_coeff_table_3_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal dct_1d_dct_coeff_table_3_q0 : STD_LOGIC_VECTOR (14 downto 0);
    signal dct_1d_dct_coeff_table_4_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal dct_1d_dct_coeff_table_4_q0 : STD_LOGIC_VECTOR (14 downto 0);
    signal dct_1d_dct_coeff_table_5_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal dct_1d_dct_coeff_table_5_q0 : STD_LOGIC_VECTOR (14 downto 0);
    signal dct_1d_dct_coeff_table_6_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal dct_1d_dct_coeff_table_6_q0 : STD_LOGIC_VECTOR (14 downto 0);
    signal dct_1d_dct_coeff_table_7_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal dct_1d_dct_coeff_table_7_q0 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal sext_ln46_5_cast_fu_249_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln46_5_cast_reg_437 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln46_2_cast_fu_253_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln46_2_cast_reg_442 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln46_3_cast_fu_257_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln46_3_cast_reg_447 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln46_4_cast_fu_261_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln46_4_cast_reg_452 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln46_6_cast_fu_265_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln46_6_cast_reg_457 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln46_cast_fu_269_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln46_cast_reg_462 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln46_7_cast_fu_273_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln46_7_cast_reg_467 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln46_1_cast_fu_277_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln46_1_cast_reg_472 : STD_LOGIC_VECTOR (28 downto 0);
    signal k_1_reg_477 : STD_LOGIC_VECTOR (3 downto 0);
    signal k_1_reg_477_pp0_iter1_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal k_1_reg_477_pp0_iter2_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal k_1_reg_477_pp0_iter3_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal k_1_reg_477_pp0_iter4_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal k_1_reg_477_pp0_iter5_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal k_1_reg_477_pp0_iter6_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln39_fu_301_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln39_reg_486 : STD_LOGIC_VECTOR (63 downto 0);
    signal coeff_reg_542 : STD_LOGIC_VECTOR (13 downto 0);
    signal coeff_2_reg_552 : STD_LOGIC_VECTOR (14 downto 0);
    signal coeff_4_reg_562 : STD_LOGIC_VECTOR (14 downto 0);
    signal mul_ln46_2_fu_340_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal mul_ln46_2_reg_577 : STD_LOGIC_VECTOR (28 downto 0);
    signal mul_ln46_4_fu_345_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal mul_ln46_4_reg_582 : STD_LOGIC_VECTOR (28 downto 0);
    signal mul_ln46_6_fu_350_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal mul_ln46_6_reg_587 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_391_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_398_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln46_reg_597 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_412_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln46_1_reg_602 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln46_6_fu_355_p2 : STD_LOGIC_VECTOR (28 downto 0);
    attribute use_dsp48 : string;
    attribute use_dsp48 of add_ln46_6_fu_355_p2 : signal is "no";
    signal add_ln46_6_reg_607 : STD_LOGIC_VECTOR (28 downto 0);
    signal trunc_ln_reg_612 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln46_3_fu_386_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal k_fu_74 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln39_fu_295_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_k_1 : STD_LOGIC_VECTOR (3 downto 0);
    signal dct_1d_dct_coeff_table_7_ce0_local : STD_LOGIC;
    signal dct_1d_dct_coeff_table_0_ce0_local : STD_LOGIC;
    signal dct_1d_dct_coeff_table_1_ce0_local : STD_LOGIC;
    signal dct_1d_dct_coeff_table_2_ce0_local : STD_LOGIC;
    signal dct_1d_dct_coeff_table_3_ce0_local : STD_LOGIC;
    signal dct_1d_dct_coeff_table_4_ce0_local : STD_LOGIC;
    signal dct_1d_dct_coeff_table_5_ce0_local : STD_LOGIC;
    signal dct_1d_dct_coeff_table_6_ce0_local : STD_LOGIC;
    signal dst_we0_local : STD_LOGIC;
    signal dst_ce0_local : STD_LOGIC;
    signal mul_ln46_2_fu_340_p0 : STD_LOGIC_VECTOR (13 downto 0);
    signal mul_ln46_2_fu_340_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln46_4_fu_345_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln46_6_fu_350_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln46_6_fu_355_p0 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_404_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_418_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln46_2_fu_359_p2 : STD_LOGIC_VECTOR (28 downto 0);
    attribute use_dsp48 of add_ln46_2_fu_359_p2 : signal is "no";
    signal add_ln46_7_fu_363_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal zext_ln46_2_fu_378_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln46_8_fu_381_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_fu_391_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_391_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_398_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_404_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_412_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_418_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal mul_ln46_2_fu_340_p00 : STD_LOGIC_VECTOR (28 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component dct_mul_14ns_16s_29_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (13 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component dct_mul_15s_16s_29_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (14 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component dct_mac_muladd_16s_15s_13ns_29_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (14 downto 0);
        din2 : IN STD_LOGIC_VECTOR (12 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component dct_mac_muladd_16s_15s_29s_29_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (14 downto 0);
        din2 : IN STD_LOGIC_VECTOR (28 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component dct_mac_muladd_16s_15s_29ns_29_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (14 downto 0);
        din2 : IN STD_LOGIC_VECTOR (28 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component dct_dct_1d_Pipeline_DCT_Outer_Loop_dct_1d_dct_coeff_table_0_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (13 downto 0) );
    end component;


    component dct_dct_1d_Pipeline_DCT_Outer_Loop_dct_1d_dct_coeff_table_1_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component dct_dct_1d_Pipeline_DCT_Outer_Loop_dct_1d_dct_coeff_table_2_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component dct_dct_1d_Pipeline_DCT_Outer_Loop_dct_1d_dct_coeff_table_3_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component dct_dct_1d_Pipeline_DCT_Outer_Loop_dct_1d_dct_coeff_table_4_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component dct_dct_1d_Pipeline_DCT_Outer_Loop_dct_1d_dct_coeff_table_5_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component dct_dct_1d_Pipeline_DCT_Outer_Loop_dct_1d_dct_coeff_table_6_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component dct_dct_1d_Pipeline_DCT_Outer_Loop_dct_1d_dct_coeff_table_7_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component dct_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    dct_1d_dct_coeff_table_0_U : component dct_dct_1d_Pipeline_DCT_Outer_Loop_dct_1d_dct_coeff_table_0_ROM_AUTO_1R
    generic map (
        DataWidth => 14,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => dct_1d_dct_coeff_table_0_address0,
        ce0 => dct_1d_dct_coeff_table_0_ce0_local,
        q0 => dct_1d_dct_coeff_table_0_q0);

    dct_1d_dct_coeff_table_1_U : component dct_dct_1d_Pipeline_DCT_Outer_Loop_dct_1d_dct_coeff_table_1_ROM_AUTO_1R
    generic map (
        DataWidth => 15,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => dct_1d_dct_coeff_table_1_address0,
        ce0 => dct_1d_dct_coeff_table_1_ce0_local,
        q0 => dct_1d_dct_coeff_table_1_q0);

    dct_1d_dct_coeff_table_2_U : component dct_dct_1d_Pipeline_DCT_Outer_Loop_dct_1d_dct_coeff_table_2_ROM_AUTO_1R
    generic map (
        DataWidth => 15,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => dct_1d_dct_coeff_table_2_address0,
        ce0 => dct_1d_dct_coeff_table_2_ce0_local,
        q0 => dct_1d_dct_coeff_table_2_q0);

    dct_1d_dct_coeff_table_3_U : component dct_dct_1d_Pipeline_DCT_Outer_Loop_dct_1d_dct_coeff_table_3_ROM_AUTO_1R
    generic map (
        DataWidth => 15,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => dct_1d_dct_coeff_table_3_address0,
        ce0 => dct_1d_dct_coeff_table_3_ce0_local,
        q0 => dct_1d_dct_coeff_table_3_q0);

    dct_1d_dct_coeff_table_4_U : component dct_dct_1d_Pipeline_DCT_Outer_Loop_dct_1d_dct_coeff_table_4_ROM_AUTO_1R
    generic map (
        DataWidth => 15,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => dct_1d_dct_coeff_table_4_address0,
        ce0 => dct_1d_dct_coeff_table_4_ce0_local,
        q0 => dct_1d_dct_coeff_table_4_q0);

    dct_1d_dct_coeff_table_5_U : component dct_dct_1d_Pipeline_DCT_Outer_Loop_dct_1d_dct_coeff_table_5_ROM_AUTO_1R
    generic map (
        DataWidth => 15,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => dct_1d_dct_coeff_table_5_address0,
        ce0 => dct_1d_dct_coeff_table_5_ce0_local,
        q0 => dct_1d_dct_coeff_table_5_q0);

    dct_1d_dct_coeff_table_6_U : component dct_dct_1d_Pipeline_DCT_Outer_Loop_dct_1d_dct_coeff_table_6_ROM_AUTO_1R
    generic map (
        DataWidth => 15,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => dct_1d_dct_coeff_table_6_address0,
        ce0 => dct_1d_dct_coeff_table_6_ce0_local,
        q0 => dct_1d_dct_coeff_table_6_q0);

    dct_1d_dct_coeff_table_7_U : component dct_dct_1d_Pipeline_DCT_Outer_Loop_dct_1d_dct_coeff_table_7_ROM_AUTO_1R
    generic map (
        DataWidth => 15,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => dct_1d_dct_coeff_table_7_address0,
        ce0 => dct_1d_dct_coeff_table_7_ce0_local,
        q0 => dct_1d_dct_coeff_table_7_q0);

    mul_14ns_16s_29_1_1_U3 : component dct_mul_14ns_16s_29_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 14,
        din1_WIDTH => 16,
        dout_WIDTH => 29)
    port map (
        din0 => mul_ln46_2_fu_340_p0,
        din1 => mul_ln46_2_fu_340_p1,
        dout => mul_ln46_2_fu_340_p2);

    mul_15s_16s_29_1_1_U4 : component dct_mul_15s_16s_29_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 15,
        din1_WIDTH => 16,
        dout_WIDTH => 29)
    port map (
        din0 => coeff_4_reg_562,
        din1 => mul_ln46_4_fu_345_p1,
        dout => mul_ln46_4_fu_345_p2);

    mul_15s_16s_29_1_1_U5 : component dct_mul_15s_16s_29_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 15,
        din1_WIDTH => 16,
        dout_WIDTH => 29)
    port map (
        din0 => coeff_2_reg_552,
        din1 => mul_ln46_6_fu_350_p1,
        dout => mul_ln46_6_fu_350_p2);

    mac_muladd_16s_15s_13ns_29_4_1_U6 : component dct_mac_muladd_16s_15s_13ns_29_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 15,
        din2_WIDTH => 13,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_391_p0,
        din1 => dct_1d_dct_coeff_table_7_q0,
        din2 => grp_fu_391_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_391_p3);

    mac_muladd_16s_15s_29s_29_4_1_U7 : component dct_mac_muladd_16s_15s_29s_29_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 15,
        din2_WIDTH => 29,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_398_p0,
        din1 => dct_1d_dct_coeff_table_1_q0,
        din2 => mul_ln46_2_reg_577,
        ce => ap_const_logic_1,
        dout => grp_fu_398_p3);

    mac_muladd_16s_15s_29ns_29_4_1_U8 : component dct_mac_muladd_16s_15s_29ns_29_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 15,
        din2_WIDTH => 29,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_404_p0,
        din1 => dct_1d_dct_coeff_table_6_q0,
        din2 => grp_fu_391_p3,
        ce => ap_const_logic_1,
        dout => grp_fu_404_p3);

    mac_muladd_16s_15s_29s_29_4_1_U9 : component dct_mac_muladd_16s_15s_29s_29_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 15,
        din2_WIDTH => 29,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_412_p0,
        din1 => dct_1d_dct_coeff_table_3_q0,
        din2 => mul_ln46_6_reg_587,
        ce => ap_const_logic_1,
        dout => grp_fu_412_p3);

    mac_muladd_16s_15s_29s_29_4_1_U10 : component dct_mac_muladd_16s_15s_29s_29_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 15,
        din2_WIDTH => 29,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_418_p0,
        din1 => dct_1d_dct_coeff_table_5_q0,
        din2 => mul_ln46_4_reg_582,
        ce => ap_const_logic_1,
        dout => grp_fu_418_p3);

    flow_control_loop_pipe_sequential_init_U : component dct_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter6_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    k_fu_74_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln39_fu_289_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    k_fu_74 <= add_ln39_fu_295_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    k_fu_74 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then
                add_ln46_1_reg_602 <= grp_fu_412_p3;
                add_ln46_reg_597 <= grp_fu_398_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln46_6_reg_607 <= add_ln46_6_fu_355_p2;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                coeff_2_reg_552 <= dct_1d_dct_coeff_table_2_q0;
                coeff_4_reg_562 <= dct_1d_dct_coeff_table_4_q0;
                coeff_reg_542 <= dct_1d_dct_coeff_table_0_q0;
                k_1_reg_477_pp0_iter2_reg <= k_1_reg_477_pp0_iter1_reg;
                k_1_reg_477_pp0_iter3_reg <= k_1_reg_477_pp0_iter2_reg;
                k_1_reg_477_pp0_iter4_reg <= k_1_reg_477_pp0_iter3_reg;
                k_1_reg_477_pp0_iter5_reg <= k_1_reg_477_pp0_iter4_reg;
                k_1_reg_477_pp0_iter6_reg <= k_1_reg_477_pp0_iter5_reg;
                mul_ln46_2_reg_577 <= mul_ln46_2_fu_340_p2;
                mul_ln46_4_reg_582 <= mul_ln46_4_fu_345_p2;
                mul_ln46_6_reg_587 <= mul_ln46_6_fu_350_p2;
                trunc_ln_reg_612 <= add_ln46_7_fu_363_p2(28 downto 13);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                k_1_reg_477 <= ap_sig_allocacmp_k_1;
                k_1_reg_477_pp0_iter1_reg <= k_1_reg_477;
                sext_ln46_1_cast_reg_472 <= sext_ln46_1_cast_fu_277_p1;
                sext_ln46_2_cast_reg_442 <= sext_ln46_2_cast_fu_253_p1;
                sext_ln46_3_cast_reg_447 <= sext_ln46_3_cast_fu_257_p1;
                sext_ln46_4_cast_reg_452 <= sext_ln46_4_cast_fu_261_p1;
                sext_ln46_5_cast_reg_437 <= sext_ln46_5_cast_fu_249_p1;
                sext_ln46_6_cast_reg_457 <= sext_ln46_6_cast_fu_265_p1;
                sext_ln46_7_cast_reg_467 <= sext_ln46_7_cast_fu_273_p1;
                sext_ln46_cast_reg_462 <= sext_ln46_cast_fu_269_p1;
                    zext_ln39_reg_486(3 downto 0) <= zext_ln39_fu_301_p1(3 downto 0);
            end if;
        end if;
    end process;
    zext_ln39_reg_486(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln39_fu_295_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_k_1) + unsigned(ap_const_lv4_1));
    add_ln46_2_fu_359_p2 <= std_logic_vector(signed(add_ln46_1_reg_602) + signed(add_ln46_reg_597));
    add_ln46_6_fu_355_p0 <= grp_fu_404_p3;
    add_ln46_6_fu_355_p2 <= std_logic_vector(signed(add_ln46_6_fu_355_p0) + signed(grp_fu_418_p3));
    add_ln46_7_fu_363_p2 <= std_logic_vector(unsigned(add_ln46_6_reg_607) + unsigned(add_ln46_2_fu_359_p2));
    add_ln46_8_fu_381_p2 <= std_logic_vector(unsigned(zext_ln46_1) + unsigned(zext_ln46_2_fu_378_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln39_fu_289_p2)
    begin
        if (((icmp_ln39_fu_289_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter6_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter6_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7)
    begin
        if (((ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_k_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, k_fu_74, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_k_1 <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_k_1 <= k_fu_74;
        end if; 
    end process;

    dct_1d_dct_coeff_table_0_address0 <= zext_ln39_reg_486(3 - 1 downto 0);

    dct_1d_dct_coeff_table_0_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            dct_1d_dct_coeff_table_0_ce0_local <= ap_const_logic_1;
        else 
            dct_1d_dct_coeff_table_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    dct_1d_dct_coeff_table_1_address0 <= zext_ln39_reg_486(3 - 1 downto 0);

    dct_1d_dct_coeff_table_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            dct_1d_dct_coeff_table_1_ce0_local <= ap_const_logic_1;
        else 
            dct_1d_dct_coeff_table_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    dct_1d_dct_coeff_table_2_address0 <= zext_ln39_reg_486(3 - 1 downto 0);

    dct_1d_dct_coeff_table_2_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            dct_1d_dct_coeff_table_2_ce0_local <= ap_const_logic_1;
        else 
            dct_1d_dct_coeff_table_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    dct_1d_dct_coeff_table_3_address0 <= zext_ln39_reg_486(3 - 1 downto 0);

    dct_1d_dct_coeff_table_3_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            dct_1d_dct_coeff_table_3_ce0_local <= ap_const_logic_1;
        else 
            dct_1d_dct_coeff_table_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    dct_1d_dct_coeff_table_4_address0 <= zext_ln39_reg_486(3 - 1 downto 0);

    dct_1d_dct_coeff_table_4_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            dct_1d_dct_coeff_table_4_ce0_local <= ap_const_logic_1;
        else 
            dct_1d_dct_coeff_table_4_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    dct_1d_dct_coeff_table_5_address0 <= zext_ln39_reg_486(3 - 1 downto 0);

    dct_1d_dct_coeff_table_5_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            dct_1d_dct_coeff_table_5_ce0_local <= ap_const_logic_1;
        else 
            dct_1d_dct_coeff_table_5_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    dct_1d_dct_coeff_table_6_address0 <= zext_ln39_reg_486(3 - 1 downto 0);

    dct_1d_dct_coeff_table_6_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            dct_1d_dct_coeff_table_6_ce0_local <= ap_const_logic_1;
        else 
            dct_1d_dct_coeff_table_6_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    dct_1d_dct_coeff_table_7_address0 <= zext_ln39_fu_301_p1(3 - 1 downto 0);

    dct_1d_dct_coeff_table_7_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            dct_1d_dct_coeff_table_7_ce0_local <= ap_const_logic_1;
        else 
            dct_1d_dct_coeff_table_7_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    dst_address0 <= zext_ln46_3_fu_386_p1(6 - 1 downto 0);
    dst_ce0 <= dst_ce0_local;

    dst_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter7, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1))) then 
            dst_ce0_local <= ap_const_logic_1;
        else 
            dst_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    dst_d0 <= trunc_ln_reg_612;
    dst_we0 <= dst_we0_local;

    dst_we0_local_assign_proc : process(ap_enable_reg_pp0_iter7, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1))) then 
            dst_we0_local <= ap_const_logic_1;
        else 
            dst_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_391_p0 <= sext_ln46_7_cast_reg_467(16 - 1 downto 0);
    grp_fu_391_p2 <= ap_const_lv29_1000(13 - 1 downto 0);
    grp_fu_398_p0 <= sext_ln46_1_cast_reg_472(16 - 1 downto 0);
    grp_fu_404_p0 <= sext_ln46_6_cast_reg_457(16 - 1 downto 0);
    grp_fu_412_p0 <= sext_ln46_3_cast_reg_447(16 - 1 downto 0);
    grp_fu_418_p0 <= sext_ln46_5_cast_reg_437(16 - 1 downto 0);
    icmp_ln39_fu_289_p2 <= "1" when (ap_sig_allocacmp_k_1 = ap_const_lv4_8) else "0";
    mul_ln46_2_fu_340_p0 <= mul_ln46_2_fu_340_p00(14 - 1 downto 0);
    mul_ln46_2_fu_340_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(coeff_reg_542),29));
    mul_ln46_2_fu_340_p1 <= sext_ln46_cast_reg_462(16 - 1 downto 0);
    mul_ln46_4_fu_345_p1 <= sext_ln46_4_cast_reg_452(16 - 1 downto 0);
    mul_ln46_6_fu_350_p1 <= sext_ln46_2_cast_reg_442(16 - 1 downto 0);
        sext_ln46_1_cast_fu_277_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln46_1),29));

        sext_ln46_2_cast_fu_253_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln46_2),29));

        sext_ln46_3_cast_fu_257_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln46_3),29));

        sext_ln46_4_cast_fu_261_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln46_4),29));

        sext_ln46_5_cast_fu_249_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln46_5),29));

        sext_ln46_6_cast_fu_265_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln46_6),29));

        sext_ln46_7_cast_fu_273_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln46_7),29));

        sext_ln46_cast_fu_269_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln46),29));

    zext_ln39_fu_301_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_k_1),64));
    zext_ln46_2_fu_378_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(k_1_reg_477_pp0_iter6_reg),6));
    zext_ln46_3_fu_386_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln46_8_fu_381_p2),64));
end behav;
