// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module yuv_filter_entry_proc (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        out_channels_ch1,
        out_channels_ch1_c_din,
        out_channels_ch1_c_full_n,
        out_channels_ch1_c_write,
        out_channels_ch1_c_num_data_valid,
        out_channels_ch1_c_fifo_cap,
        out_channels_ch2,
        out_channels_ch2_c_din,
        out_channels_ch2_c_full_n,
        out_channels_ch2_c_write,
        out_channels_ch2_c_num_data_valid,
        out_channels_ch2_c_fifo_cap,
        out_channels_ch3,
        out_channels_ch3_c_din,
        out_channels_ch3_c_full_n,
        out_channels_ch3_c_write,
        out_channels_ch3_c_num_data_valid,
        out_channels_ch3_c_fifo_cap,
        out_width,
        out_width_c_din,
        out_width_c_full_n,
        out_width_c_write,
        out_width_c_num_data_valid,
        out_width_c_fifo_cap,
        out_height,
        out_height_c_din,
        out_height_c_full_n,
        out_height_c_write,
        out_height_c_num_data_valid,
        out_height_c_fifo_cap,
        Y_scale,
        Y_scale_c_din,
        Y_scale_c_full_n,
        Y_scale_c_write,
        Y_scale_c_num_data_valid,
        Y_scale_c_fifo_cap,
        U_scale,
        U_scale_c_din,
        U_scale_c_full_n,
        U_scale_c_write,
        U_scale_c_num_data_valid,
        U_scale_c_fifo_cap,
        V_scale,
        V_scale_c_din,
        V_scale_c_full_n,
        V_scale_c_write,
        V_scale_c_num_data_valid,
        V_scale_c_fifo_cap
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [63:0] out_channels_ch1;
output  [63:0] out_channels_ch1_c_din;
input   out_channels_ch1_c_full_n;
output   out_channels_ch1_c_write;
input  [2:0] out_channels_ch1_c_num_data_valid;
input  [2:0] out_channels_ch1_c_fifo_cap;
input  [63:0] out_channels_ch2;
output  [63:0] out_channels_ch2_c_din;
input   out_channels_ch2_c_full_n;
output   out_channels_ch2_c_write;
input  [2:0] out_channels_ch2_c_num_data_valid;
input  [2:0] out_channels_ch2_c_fifo_cap;
input  [63:0] out_channels_ch3;
output  [63:0] out_channels_ch3_c_din;
input   out_channels_ch3_c_full_n;
output   out_channels_ch3_c_write;
input  [2:0] out_channels_ch3_c_num_data_valid;
input  [2:0] out_channels_ch3_c_fifo_cap;
input  [63:0] out_width;
output  [63:0] out_width_c_din;
input   out_width_c_full_n;
output   out_width_c_write;
input  [2:0] out_width_c_num_data_valid;
input  [2:0] out_width_c_fifo_cap;
input  [63:0] out_height;
output  [63:0] out_height_c_din;
input   out_height_c_full_n;
output   out_height_c_write;
input  [2:0] out_height_c_num_data_valid;
input  [2:0] out_height_c_fifo_cap;
input  [7:0] Y_scale;
output  [7:0] Y_scale_c_din;
input   Y_scale_c_full_n;
output   Y_scale_c_write;
input  [2:0] Y_scale_c_num_data_valid;
input  [2:0] Y_scale_c_fifo_cap;
input  [7:0] U_scale;
output  [7:0] U_scale_c_din;
input   U_scale_c_full_n;
output   U_scale_c_write;
input  [2:0] U_scale_c_num_data_valid;
input  [2:0] U_scale_c_fifo_cap;
input  [7:0] V_scale;
output  [7:0] V_scale_c_din;
input   V_scale_c_full_n;
output   V_scale_c_write;
input  [2:0] V_scale_c_num_data_valid;
input  [2:0] V_scale_c_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;
reg out_channels_ch1_c_write;
reg out_channels_ch2_c_write;
reg out_channels_ch3_c_write;
reg out_width_c_write;
reg out_height_c_write;
reg Y_scale_c_write;
reg U_scale_c_write;
reg V_scale_c_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    out_channels_ch1_c_blk_n;
reg    out_channels_ch2_c_blk_n;
reg    out_channels_ch3_c_blk_n;
reg    out_width_c_blk_n;
reg    out_height_c_blk_n;
reg    Y_scale_c_blk_n;
reg    U_scale_c_blk_n;
reg    V_scale_c_blk_n;
reg    ap_block_state1;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        U_scale_c_blk_n = U_scale_c_full_n;
    end else begin
        U_scale_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        U_scale_c_write = 1'b1;
    end else begin
        U_scale_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        V_scale_c_blk_n = V_scale_c_full_n;
    end else begin
        V_scale_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        V_scale_c_write = 1'b1;
    end else begin
        V_scale_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        Y_scale_c_blk_n = Y_scale_c_full_n;
    end else begin
        Y_scale_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        Y_scale_c_write = 1'b1;
    end else begin
        Y_scale_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        out_channels_ch1_c_blk_n = out_channels_ch1_c_full_n;
    end else begin
        out_channels_ch1_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        out_channels_ch1_c_write = 1'b1;
    end else begin
        out_channels_ch1_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        out_channels_ch2_c_blk_n = out_channels_ch2_c_full_n;
    end else begin
        out_channels_ch2_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        out_channels_ch2_c_write = 1'b1;
    end else begin
        out_channels_ch2_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        out_channels_ch3_c_blk_n = out_channels_ch3_c_full_n;
    end else begin
        out_channels_ch3_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        out_channels_ch3_c_write = 1'b1;
    end else begin
        out_channels_ch3_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        out_height_c_blk_n = out_height_c_full_n;
    end else begin
        out_height_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        out_height_c_write = 1'b1;
    end else begin
        out_height_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        out_width_c_blk_n = out_width_c_full_n;
    end else begin
        out_width_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        out_width_c_write = 1'b1;
    end else begin
        out_width_c_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign U_scale_c_din = U_scale;

assign V_scale_c_din = V_scale;

assign Y_scale_c_din = Y_scale;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (out_height_c_full_n == 1'b0) | (out_width_c_full_n == 1'b0) | (out_channels_ch3_c_full_n == 1'b0) | (out_channels_ch2_c_full_n == 1'b0) | (out_channels_ch1_c_full_n == 1'b0) | (1'b0 == V_scale_c_full_n) | (1'b0 == U_scale_c_full_n) | (1'b0 == Y_scale_c_full_n) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign out_channels_ch1_c_din = out_channels_ch1;

assign out_channels_ch2_c_din = out_channels_ch2;

assign out_channels_ch3_c_din = out_channels_ch3;

assign out_height_c_din = out_height;

assign out_width_c_din = out_width;

assign start_out = real_start;

endmodule //yuv_filter_entry_proc
