// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module yuv_filter_yuv_filter_Pipeline_RGB2YUV_LOOP_X_RGB2YUV_LOOP_Y (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_0_AWVALID,
        m_axi_gmem_0_AWREADY,
        m_axi_gmem_0_AWADDR,
        m_axi_gmem_0_AWID,
        m_axi_gmem_0_AWLEN,
        m_axi_gmem_0_AWSIZE,
        m_axi_gmem_0_AWBURST,
        m_axi_gmem_0_AWLOCK,
        m_axi_gmem_0_AWCACHE,
        m_axi_gmem_0_AWPROT,
        m_axi_gmem_0_AWQOS,
        m_axi_gmem_0_AWREGION,
        m_axi_gmem_0_AWUSER,
        m_axi_gmem_0_WVALID,
        m_axi_gmem_0_WREADY,
        m_axi_gmem_0_WDATA,
        m_axi_gmem_0_WSTRB,
        m_axi_gmem_0_WLAST,
        m_axi_gmem_0_WID,
        m_axi_gmem_0_WUSER,
        m_axi_gmem_0_ARVALID,
        m_axi_gmem_0_ARREADY,
        m_axi_gmem_0_ARADDR,
        m_axi_gmem_0_ARID,
        m_axi_gmem_0_ARLEN,
        m_axi_gmem_0_ARSIZE,
        m_axi_gmem_0_ARBURST,
        m_axi_gmem_0_ARLOCK,
        m_axi_gmem_0_ARCACHE,
        m_axi_gmem_0_ARPROT,
        m_axi_gmem_0_ARQOS,
        m_axi_gmem_0_ARREGION,
        m_axi_gmem_0_ARUSER,
        m_axi_gmem_0_RVALID,
        m_axi_gmem_0_RREADY,
        m_axi_gmem_0_RDATA,
        m_axi_gmem_0_RLAST,
        m_axi_gmem_0_RID,
        m_axi_gmem_0_RFIFONUM,
        m_axi_gmem_0_RUSER,
        m_axi_gmem_0_RRESP,
        m_axi_gmem_0_BVALID,
        m_axi_gmem_0_BREADY,
        m_axi_gmem_0_BRESP,
        m_axi_gmem_0_BID,
        m_axi_gmem_0_BUSER,
        mul_ln30,
        height,
        p_yuv_channels_ch1_address0,
        p_yuv_channels_ch1_ce0,
        p_yuv_channels_ch1_we0,
        p_yuv_channels_ch1_d0,
        p_yuv_channels_ch2_address0,
        p_yuv_channels_ch2_ce0,
        p_yuv_channels_ch2_we0,
        p_yuv_channels_ch2_d0,
        p_yuv_channels_ch3_address0,
        p_yuv_channels_ch3_ce0,
        p_yuv_channels_ch3_we0,
        p_yuv_channels_ch3_d0,
        in_channels_ch1,
        in_channels_ch2,
        in_channels_ch3
);

parameter    ap_ST_fsm_pp0_stage0 = 3'd1;
parameter    ap_ST_fsm_pp0_stage1 = 3'd2;
parameter    ap_ST_fsm_pp0_stage2 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_0_AWVALID;
input   m_axi_gmem_0_AWREADY;
output  [63:0] m_axi_gmem_0_AWADDR;
output  [0:0] m_axi_gmem_0_AWID;
output  [31:0] m_axi_gmem_0_AWLEN;
output  [2:0] m_axi_gmem_0_AWSIZE;
output  [1:0] m_axi_gmem_0_AWBURST;
output  [1:0] m_axi_gmem_0_AWLOCK;
output  [3:0] m_axi_gmem_0_AWCACHE;
output  [2:0] m_axi_gmem_0_AWPROT;
output  [3:0] m_axi_gmem_0_AWQOS;
output  [3:0] m_axi_gmem_0_AWREGION;
output  [0:0] m_axi_gmem_0_AWUSER;
output   m_axi_gmem_0_WVALID;
input   m_axi_gmem_0_WREADY;
output  [15:0] m_axi_gmem_0_WDATA;
output  [1:0] m_axi_gmem_0_WSTRB;
output   m_axi_gmem_0_WLAST;
output  [0:0] m_axi_gmem_0_WID;
output  [0:0] m_axi_gmem_0_WUSER;
output   m_axi_gmem_0_ARVALID;
input   m_axi_gmem_0_ARREADY;
output  [63:0] m_axi_gmem_0_ARADDR;
output  [0:0] m_axi_gmem_0_ARID;
output  [31:0] m_axi_gmem_0_ARLEN;
output  [2:0] m_axi_gmem_0_ARSIZE;
output  [1:0] m_axi_gmem_0_ARBURST;
output  [1:0] m_axi_gmem_0_ARLOCK;
output  [3:0] m_axi_gmem_0_ARCACHE;
output  [2:0] m_axi_gmem_0_ARPROT;
output  [3:0] m_axi_gmem_0_ARQOS;
output  [3:0] m_axi_gmem_0_ARREGION;
output  [0:0] m_axi_gmem_0_ARUSER;
input   m_axi_gmem_0_RVALID;
output   m_axi_gmem_0_RREADY;
input  [15:0] m_axi_gmem_0_RDATA;
input   m_axi_gmem_0_RLAST;
input  [0:0] m_axi_gmem_0_RID;
input  [9:0] m_axi_gmem_0_RFIFONUM;
input  [0:0] m_axi_gmem_0_RUSER;
input  [1:0] m_axi_gmem_0_RRESP;
input   m_axi_gmem_0_BVALID;
output   m_axi_gmem_0_BREADY;
input  [1:0] m_axi_gmem_0_BRESP;
input  [0:0] m_axi_gmem_0_BID;
input  [0:0] m_axi_gmem_0_BUSER;
input  [31:0] mul_ln30;
input  [15:0] height;
output  [21:0] p_yuv_channels_ch1_address0;
output   p_yuv_channels_ch1_ce0;
output   p_yuv_channels_ch1_we0;
output  [7:0] p_yuv_channels_ch1_d0;
output  [21:0] p_yuv_channels_ch2_address0;
output   p_yuv_channels_ch2_ce0;
output   p_yuv_channels_ch2_we0;
output  [7:0] p_yuv_channels_ch2_d0;
output  [21:0] p_yuv_channels_ch3_address0;
output   p_yuv_channels_ch3_ce0;
output   p_yuv_channels_ch3_we0;
output  [7:0] p_yuv_channels_ch3_d0;
input  [63:0] in_channels_ch1;
input  [63:0] in_channels_ch2;
input  [63:0] in_channels_ch3;

reg ap_idle;
reg m_axi_gmem_0_ARVALID;
reg[63:0] m_axi_gmem_0_ARADDR;
reg m_axi_gmem_0_RREADY;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_enable_reg_pp0_iter23;
reg    ap_enable_reg_pp0_iter24;
reg    ap_enable_reg_pp0_iter25;
reg    ap_enable_reg_pp0_iter26;
reg    ap_enable_reg_pp0_iter27;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage2;
reg    ap_block_pp0_stage2_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] icmp_ln75_reg_870;
reg    ap_condition_exit_pp0_iter0_stage2;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem_blk_n_AR;
wire    ap_block_pp0_stage0_grp1;
reg    ap_block_pp0_stage0_subdone_grp1_done_reg;
reg    ap_block_pp0_stage0_subdone_grp1;
reg    ap_block_pp0_stage0_subdone;
reg    gmem_blk_n_R;
wire    ap_block_pp0_stage2_grp3;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_grp2;
reg    ap_block_pp0_stage1_subdone_grp2_done_reg;
reg    ap_block_pp0_stage1_subdone_grp2;
reg    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage0_grp5;
reg    ap_block_pp0_stage0_subdone_grp5_done_reg;
reg    ap_block_pp0_stage0_subdone_grp5;
wire    ap_block_pp0_stage1_grp6;
reg    ap_block_pp0_stage1_subdone_grp6_done_reg;
reg    ap_block_pp0_stage1_subdone_grp6;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
wire   [0:0] icmp_ln75_fu_275_p2;
reg    ap_block_pp0_stage1_11001;
reg   [0:0] icmp_ln75_reg_870_pp0_iter1_reg;
reg   [0:0] icmp_ln75_reg_870_pp0_iter2_reg;
reg   [0:0] icmp_ln75_reg_870_pp0_iter3_reg;
reg   [0:0] icmp_ln75_reg_870_pp0_iter4_reg;
reg   [0:0] icmp_ln75_reg_870_pp0_iter5_reg;
reg   [0:0] icmp_ln75_reg_870_pp0_iter6_reg;
reg   [0:0] icmp_ln75_reg_870_pp0_iter7_reg;
reg   [0:0] icmp_ln75_reg_870_pp0_iter8_reg;
reg   [0:0] icmp_ln75_reg_870_pp0_iter9_reg;
reg   [0:0] icmp_ln75_reg_870_pp0_iter10_reg;
reg   [0:0] icmp_ln75_reg_870_pp0_iter11_reg;
reg   [0:0] icmp_ln75_reg_870_pp0_iter12_reg;
reg   [0:0] icmp_ln75_reg_870_pp0_iter13_reg;
reg   [0:0] icmp_ln75_reg_870_pp0_iter14_reg;
reg   [0:0] icmp_ln75_reg_870_pp0_iter15_reg;
reg   [0:0] icmp_ln75_reg_870_pp0_iter16_reg;
reg   [0:0] icmp_ln75_reg_870_pp0_iter17_reg;
reg   [0:0] icmp_ln75_reg_870_pp0_iter18_reg;
reg   [0:0] icmp_ln75_reg_870_pp0_iter19_reg;
reg   [0:0] icmp_ln75_reg_870_pp0_iter20_reg;
reg   [0:0] icmp_ln75_reg_870_pp0_iter21_reg;
reg   [0:0] icmp_ln75_reg_870_pp0_iter22_reg;
reg   [0:0] icmp_ln75_reg_870_pp0_iter23_reg;
reg   [0:0] icmp_ln75_reg_870_pp0_iter24_reg;
reg   [0:0] icmp_ln75_reg_870_pp0_iter25_reg;
wire   [15:0] select_ln60_fu_303_p3;
reg   [15:0] select_ln60_reg_874;
wire   [26:0] add_ln86_1_fu_343_p2;
reg   [26:0] add_ln86_1_reg_881;
wire   [21:0] trunc_ln75_fu_349_p1;
reg   [21:0] trunc_ln75_reg_886;
wire   [21:0] add_ln86_fu_372_p2;
reg   [21:0] add_ln86_reg_891;
wire    ap_block_pp0_stage2_11001_grp0;
reg    ap_block_pp0_stage2_subdone_grp0_done_reg;
wire    ap_block_pp0_stage2_subdone_grp0;
reg   [21:0] add_ln86_reg_891_pp0_iter1_reg;
reg   [21:0] add_ln86_reg_891_pp0_iter2_reg;
reg   [21:0] add_ln86_reg_891_pp0_iter3_reg;
reg   [21:0] add_ln86_reg_891_pp0_iter4_reg;
reg   [21:0] add_ln86_reg_891_pp0_iter5_reg;
reg   [21:0] add_ln86_reg_891_pp0_iter6_reg;
reg   [21:0] add_ln86_reg_891_pp0_iter7_reg;
reg   [21:0] add_ln86_reg_891_pp0_iter8_reg;
reg   [21:0] add_ln86_reg_891_pp0_iter9_reg;
reg   [21:0] add_ln86_reg_891_pp0_iter10_reg;
reg   [21:0] add_ln86_reg_891_pp0_iter11_reg;
reg   [21:0] add_ln86_reg_891_pp0_iter12_reg;
reg   [21:0] add_ln86_reg_891_pp0_iter13_reg;
reg   [21:0] add_ln86_reg_891_pp0_iter14_reg;
reg   [21:0] add_ln86_reg_891_pp0_iter15_reg;
reg   [21:0] add_ln86_reg_891_pp0_iter16_reg;
reg   [21:0] add_ln86_reg_891_pp0_iter17_reg;
reg   [21:0] add_ln86_reg_891_pp0_iter18_reg;
reg   [21:0] add_ln86_reg_891_pp0_iter19_reg;
reg   [21:0] add_ln86_reg_891_pp0_iter20_reg;
reg   [21:0] add_ln86_reg_891_pp0_iter21_reg;
reg   [21:0] add_ln86_reg_891_pp0_iter22_reg;
reg   [21:0] add_ln86_reg_891_pp0_iter23_reg;
reg   [21:0] add_ln86_reg_891_pp0_iter24_reg;
reg   [21:0] add_ln86_reg_891_pp0_iter25_reg;
reg   [63:0] gmem_addr_reg_896;
reg    ap_block_pp0_stage2_11001_grp3;
wire   [0:0] trunc_ln80_fu_408_p1;
reg   [0:0] trunc_ln80_reg_902;
reg   [0:0] trunc_ln80_reg_902_pp0_iter1_reg;
reg   [0:0] trunc_ln80_reg_902_pp0_iter2_reg;
reg   [0:0] trunc_ln80_reg_902_pp0_iter3_reg;
reg   [0:0] trunc_ln80_reg_902_pp0_iter4_reg;
reg   [0:0] trunc_ln80_reg_902_pp0_iter5_reg;
reg   [0:0] trunc_ln80_reg_902_pp0_iter6_reg;
reg   [0:0] trunc_ln80_reg_902_pp0_iter7_reg;
reg   [0:0] trunc_ln80_reg_902_pp0_iter8_reg;
reg   [0:0] trunc_ln80_reg_902_pp0_iter9_reg;
reg   [0:0] trunc_ln80_reg_902_pp0_iter10_reg;
reg   [0:0] trunc_ln80_reg_902_pp0_iter11_reg;
reg   [0:0] trunc_ln80_reg_902_pp0_iter12_reg;
reg   [0:0] trunc_ln80_reg_902_pp0_iter13_reg;
reg   [0:0] trunc_ln80_reg_902_pp0_iter14_reg;
reg   [0:0] trunc_ln80_reg_902_pp0_iter15_reg;
reg   [0:0] trunc_ln80_reg_902_pp0_iter16_reg;
reg   [0:0] trunc_ln80_reg_902_pp0_iter17_reg;
reg   [0:0] trunc_ln80_reg_902_pp0_iter18_reg;
reg   [0:0] trunc_ln80_reg_902_pp0_iter19_reg;
reg   [0:0] trunc_ln80_reg_902_pp0_iter20_reg;
reg   [0:0] trunc_ln80_reg_902_pp0_iter21_reg;
reg   [0:0] trunc_ln80_reg_902_pp0_iter22_reg;
reg   [0:0] trunc_ln80_reg_902_pp0_iter23_reg;
reg   [0:0] trunc_ln80_reg_902_pp0_iter24_reg;
reg   [63:0] gmem_addr_3_reg_907;
wire   [0:0] trunc_ln81_fu_443_p1;
reg   [0:0] trunc_ln81_reg_913;
reg   [0:0] trunc_ln81_reg_913_pp0_iter1_reg;
reg   [0:0] trunc_ln81_reg_913_pp0_iter2_reg;
reg   [0:0] trunc_ln81_reg_913_pp0_iter3_reg;
reg   [0:0] trunc_ln81_reg_913_pp0_iter4_reg;
reg   [0:0] trunc_ln81_reg_913_pp0_iter5_reg;
reg   [0:0] trunc_ln81_reg_913_pp0_iter6_reg;
reg   [0:0] trunc_ln81_reg_913_pp0_iter7_reg;
reg   [0:0] trunc_ln81_reg_913_pp0_iter8_reg;
reg   [0:0] trunc_ln81_reg_913_pp0_iter9_reg;
reg   [0:0] trunc_ln81_reg_913_pp0_iter10_reg;
reg   [0:0] trunc_ln81_reg_913_pp0_iter11_reg;
reg   [0:0] trunc_ln81_reg_913_pp0_iter12_reg;
reg   [0:0] trunc_ln81_reg_913_pp0_iter13_reg;
reg   [0:0] trunc_ln81_reg_913_pp0_iter14_reg;
reg   [0:0] trunc_ln81_reg_913_pp0_iter15_reg;
reg   [0:0] trunc_ln81_reg_913_pp0_iter16_reg;
reg   [0:0] trunc_ln81_reg_913_pp0_iter17_reg;
reg   [0:0] trunc_ln81_reg_913_pp0_iter18_reg;
reg   [0:0] trunc_ln81_reg_913_pp0_iter19_reg;
reg   [0:0] trunc_ln81_reg_913_pp0_iter20_reg;
reg   [0:0] trunc_ln81_reg_913_pp0_iter21_reg;
reg   [0:0] trunc_ln81_reg_913_pp0_iter22_reg;
reg   [0:0] trunc_ln81_reg_913_pp0_iter23_reg;
reg   [0:0] trunc_ln81_reg_913_pp0_iter24_reg;
reg   [63:0] gmem_addr_4_reg_918;
wire   [0:0] trunc_ln82_fu_478_p1;
reg   [0:0] trunc_ln82_reg_924;
reg   [0:0] trunc_ln82_reg_924_pp0_iter1_reg;
reg   [0:0] trunc_ln82_reg_924_pp0_iter2_reg;
reg   [0:0] trunc_ln82_reg_924_pp0_iter3_reg;
reg   [0:0] trunc_ln82_reg_924_pp0_iter4_reg;
reg   [0:0] trunc_ln82_reg_924_pp0_iter5_reg;
reg   [0:0] trunc_ln82_reg_924_pp0_iter6_reg;
reg   [0:0] trunc_ln82_reg_924_pp0_iter7_reg;
reg   [0:0] trunc_ln82_reg_924_pp0_iter8_reg;
reg   [0:0] trunc_ln82_reg_924_pp0_iter9_reg;
reg   [0:0] trunc_ln82_reg_924_pp0_iter10_reg;
reg   [0:0] trunc_ln82_reg_924_pp0_iter11_reg;
reg   [0:0] trunc_ln82_reg_924_pp0_iter12_reg;
reg   [0:0] trunc_ln82_reg_924_pp0_iter13_reg;
reg   [0:0] trunc_ln82_reg_924_pp0_iter14_reg;
reg   [0:0] trunc_ln82_reg_924_pp0_iter15_reg;
reg   [0:0] trunc_ln82_reg_924_pp0_iter16_reg;
reg   [0:0] trunc_ln82_reg_924_pp0_iter17_reg;
reg   [0:0] trunc_ln82_reg_924_pp0_iter18_reg;
reg   [0:0] trunc_ln82_reg_924_pp0_iter19_reg;
reg   [0:0] trunc_ln82_reg_924_pp0_iter20_reg;
reg   [0:0] trunc_ln82_reg_924_pp0_iter21_reg;
reg   [0:0] trunc_ln82_reg_924_pp0_iter22_reg;
reg   [0:0] trunc_ln82_reg_924_pp0_iter23_reg;
reg   [0:0] trunc_ln82_reg_924_pp0_iter24_reg;
reg   [15:0] gmem_addr_read_reg_929;
wire   [7:0] R_fu_508_p1;
reg   [7:0] R_reg_934;
reg   [7:0] R_reg_934_pp0_iter26_reg;
reg   [15:0] gmem_addr_3_read_reg_940;
reg    ap_block_pp0_stage0_11001_grp5;
wire   [14:0] zext_ln83_fu_512_p1;
reg   [14:0] zext_ln83_reg_945;
wire   [7:0] G_fu_532_p1;
reg   [7:0] G_reg_951;
wire    ap_block_pp0_stage1_11001_grp0;
reg    ap_block_pp0_stage1_subdone_grp0_done_reg;
wire    ap_block_pp0_stage1_subdone_grp0;
reg   [15:0] gmem_addr_4_read_reg_957;
reg    ap_block_pp0_stage1_11001_grp6;
wire   [7:0] B_fu_552_p1;
reg   [7:0] B_reg_962;
wire   [15:0] zext_ln83_1_fu_556_p1;
reg   [15:0] zext_ln83_1_reg_969;
wire  signed [15:0] mul_ln84_fu_563_p2;
wire   [15:0] add_ln83_3_fu_580_p2;
reg   [15:0] add_ln83_3_reg_985;
reg   [0:0] bit_sel1_reg_990;
reg   [6:0] part_sel1_reg_995;
wire   [15:0] mul_ln85_fu_642_p2;
wire   [13:0] add_ln85_1_fu_674_p2;
reg   [13:0] add_ln85_1_reg_1005;
wire   [63:0] zext_ln86_3_fu_680_p1;
reg   [63:0] zext_ln86_3_reg_1010;
reg   [0:0] bit_sel_reg_1016;
reg   [6:0] part_sel_reg_1021;
reg   [7:0] trunc_ln2_reg_1026;
reg    ap_block_state4_io_grp1;
wire    ap_block_pp0_stage1_grp0;
wire    ap_block_pp0_stage2_grp0;
wire    ap_block_pp0_stage0_grp0;
wire  signed [63:0] sext_ln80_fu_398_p1;
wire  signed [63:0] sext_ln81_fu_433_p1;
wire  signed [63:0] sext_ln82_fu_468_p1;
reg    ap_block_pp0_stage0_11001_grp1;
reg    ap_block_pp0_stage1_11001_grp2;
reg   [15:0] y_fu_140;
wire   [15:0] add_ln78_fu_482_p2;
wire    ap_loop_init;
wire    ap_block_pp0_stage1;
reg   [15:0] x_fu_144;
wire   [15:0] select_ln75_fu_311_p3;
reg   [31:0] indvar_flatten_fu_148;
wire   [31:0] add_ln75_1_fu_280_p2;
reg    p_yuv_channels_ch2_we0_local;
wire   [7:0] U_fu_689_p3;
reg    p_yuv_channels_ch2_ce0_local;
reg    p_yuv_channels_ch3_we0_local;
wire   [7:0] V_fu_784_p3;
reg    p_yuv_channels_ch3_ce0_local;
reg    p_yuv_channels_ch1_we0_local;
wire   [7:0] Y_fu_792_p2;
reg    p_yuv_channels_ch1_ce0_local;
wire   [0:0] icmp_ln78_fu_298_p2;
wire   [15:0] add_ln75_fu_292_p2;
wire   [25:0] tmp_fu_319_p3;
wire   [23:0] tmp_10_fu_331_p3;
wire   [26:0] zext_ln86_fu_327_p1;
wire   [26:0] zext_ln86_1_fu_339_p1;
wire   [21:0] zext_ln86_2_fu_369_p1;
wire   [63:0] zext_ln78_1_fu_366_p1;
wire   [63:0] add_ln80_1_fu_377_p2;
wire   [63:0] zext_ln78_fu_363_p1;
wire   [63:0] add_ln80_fu_382_p2;
wire   [62:0] trunc_ln80_1_fu_388_p4;
wire   [63:0] add_ln81_1_fu_412_p2;
wire   [63:0] add_ln81_fu_417_p2;
wire   [62:0] trunc_ln81_1_fu_423_p4;
wire   [63:0] add_ln82_1_fu_447_p2;
wire   [63:0] add_ln82_fu_452_p2;
wire   [62:0] trunc_ln82_1_fu_458_p4;
wire   [3:0] shl_ln_fu_492_p3;
wire   [15:0] zext_ln80_fu_499_p1;
wire   [15:0] lshr_ln80_fu_503_p2;
wire   [3:0] shl_ln1_fu_516_p3;
wire   [15:0] zext_ln81_fu_523_p1;
wire   [15:0] lshr_ln81_fu_527_p2;
wire   [3:0] shl_ln2_fu_536_p3;
wire   [15:0] zext_ln82_fu_543_p1;
wire   [15:0] lshr_ln82_fu_547_p2;
wire   [7:0] mul_ln84_fu_563_p0;
wire  signed [7:0] mul_ln84_fu_563_p1;
wire   [14:0] tmp_11_fu_569_p3;
wire   [15:0] zext_ln83_3_fu_576_p1;
wire   [11:0] tmp_14_fu_592_p3;
wire   [14:0] p_shl2_fu_585_p3;
wire   [14:0] zext_ln84_1_fu_599_p1;
wire   [14:0] sub_ln84_fu_603_p2;
wire   [14:0] add_ln84_1_fu_609_p2;
wire   [15:0] zext_ln84_fu_615_p1;
wire  signed [15:0] grp_fu_798_p3;
(* use_dsp48 = "no" *) wire   [15:0] add_ln84_2_fu_619_p2;
wire   [7:0] mul_ln85_fu_642_p0;
wire  signed [7:0] mul_ln85_fu_642_p1;
wire   [13:0] zext_ln85_1_fu_647_p1;
wire   [8:0] tmp_15_fu_657_p3;
wire   [13:0] sub_ln85_fu_651_p2;
wire   [13:0] zext_ln85_2_fu_664_p1;
wire   [13:0] sub_ln85_1_fu_668_p2;
wire   [0:0] xor_ln84_fu_684_p2;
wire  signed [15:0] sext_ln85_fu_697_p1;
wire   [15:0] grp_fu_807_p3;
(* use_dsp48 = "no" *) wire   [15:0] add_ln85_2_fu_700_p2;
wire   [13:0] tmp_12_fu_723_p3;
wire   [8:0] tmp_13_fu_734_p3;
wire   [14:0] zext_ln83_4_fu_730_p1;
wire   [14:0] zext_ln83_7_fu_741_p1;
wire   [14:0] add_ln83_4_fu_745_p2;
wire   [15:0] zext_ln83_5_fu_751_p1;
wire   [12:0] grp_fu_815_p3;
wire   [15:0] zext_ln83_6_fu_760_p1;
wire   [15:0] add_ln83_fu_755_p2;
wire   [15:0] add_ln83_2_fu_763_p2;
wire   [0:0] xor_ln85_fu_779_p2;
wire   [7:0] grp_fu_798_p0;
wire  signed [6:0] grp_fu_798_p1;
wire   [7:0] grp_fu_807_p0;
wire   [6:0] grp_fu_807_p1;
wire   [7:0] grp_fu_815_p0;
wire   [4:0] grp_fu_815_p1;
wire   [7:0] grp_fu_815_p2;
reg    grp_fu_798_ce;
reg    ap_block_pp0_stage0_11001;
reg    ap_block_pp0_stage2_11001;
reg    grp_fu_807_ce;
reg    grp_fu_815_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter26_stage0;
reg    ap_idle_pp0_0to25;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg    ap_loop_exit_ready_pp0_iter19_reg;
reg    ap_loop_exit_ready_pp0_iter20_reg;
reg    ap_loop_exit_ready_pp0_iter21_reg;
reg    ap_loop_exit_ready_pp0_iter22_reg;
reg    ap_loop_exit_ready_pp0_iter23_reg;
reg    ap_loop_exit_ready_pp0_iter24_reg;
reg    ap_loop_exit_ready_pp0_iter25_reg;
reg    ap_loop_exit_ready_pp0_iter26_reg;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0_1to27;
reg    ap_done_pending_pp0;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [14:0] grp_fu_798_p00;
wire   [12:0] grp_fu_815_p00;
wire   [15:0] mul_ln84_fu_563_p00;
reg    ap_condition_1270;
reg    ap_condition_1274;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 ap_enable_reg_pp0_iter23 = 1'b0;
#0 ap_enable_reg_pp0_iter24 = 1'b0;
#0 ap_enable_reg_pp0_iter25 = 1'b0;
#0 ap_enable_reg_pp0_iter26 = 1'b0;
#0 ap_enable_reg_pp0_iter27 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp1_done_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp2_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp5_done_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp6_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 ap_block_pp0_stage2_subdone_grp0_done_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp0_done_reg = 1'b0;
#0 y_fu_140 = 16'd0;
#0 x_fu_144 = 16'd0;
#0 indvar_flatten_fu_148 = 32'd0;
#0 ap_done_reg = 1'b0;
end

yuv_filter_mul_8ns_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8s_16_1_1_U1(
    .din0(mul_ln84_fu_563_p0),
    .din1(mul_ln84_fu_563_p1),
    .dout(mul_ln84_fu_563_p2)
);

yuv_filter_mul_8ns_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8s_16_1_1_U2(
    .din0(mul_ln85_fu_642_p0),
    .din1(mul_ln85_fu_642_p1),
    .dout(mul_ln85_fu_642_p2)
);

yuv_filter_mac_muladd_8ns_7s_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_7s_16s_16_4_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_798_p0),
    .din1(grp_fu_798_p1),
    .din2(mul_ln84_fu_563_p2),
    .ce(grp_fu_798_ce),
    .dout(grp_fu_798_p3)
);

yuv_filter_mac_muladd_8ns_7ns_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_7ns_16ns_16_4_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_807_p0),
    .din1(grp_fu_807_p1),
    .din2(mul_ln85_fu_642_p2),
    .ce(grp_fu_807_ce),
    .dout(grp_fu_807_p3)
);

yuv_filter_mac_muladd_8ns_5ns_8ns_13_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .din2_WIDTH( 8 ),
    .dout_WIDTH( 13 ))
mac_muladd_8ns_5ns_8ns_13_4_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_815_p0),
    .din1(grp_fu_815_p1),
    .din2(grp_fu_815_p2),
    .ce(grp_fu_815_ce),
    .dout(grp_fu_815_p3)
);

yuv_filter_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage2),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp1)) begin
                ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp5_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp5_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp5)) begin
                ap_block_pp0_stage0_subdone_grp5_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp0)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp2_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp2_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp2)) begin
                ap_block_pp0_stage1_subdone_grp2_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp6_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp6_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp6)) begin
                ap_block_pp0_stage1_subdone_grp6_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage2_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage2)) begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_block_pp0_stage2_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage2_subdone_grp0)) begin
                ap_block_pp0_stage2_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter26_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage2)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter23 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter24 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter25 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter26 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter27 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter27 == 1'b1))) begin
            ap_enable_reg_pp0_iter27 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter26_stage0) & (ap_idle_pp0_0to25 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter10_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter26_stage0) & (ap_idle_pp0_0to25 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter11_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter26_stage0) & (ap_idle_pp0_0to25 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter12_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter26_stage0) & (ap_idle_pp0_0to25 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter13_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter26_stage0) & (ap_idle_pp0_0to25 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter14_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter26_stage0) & (ap_idle_pp0_0to25 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter15_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter26_stage0) & (ap_idle_pp0_0to25 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter16_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter26_stage0) & (ap_idle_pp0_0to25 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter17_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter26_stage0) & (ap_idle_pp0_0to25 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter18_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter26_stage0) & (ap_idle_pp0_0to25 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter19_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter26_stage0) & (ap_idle_pp0_0to25 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter26_stage0) & (ap_idle_pp0_0to25 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter20_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter26_stage0) & (ap_idle_pp0_0to25 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter21_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter26_stage0) & (ap_idle_pp0_0to25 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter22_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        ap_loop_exit_ready_pp0_iter22_reg <= ap_loop_exit_ready_pp0_iter21_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter26_stage0) & (ap_idle_pp0_0to25 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter23_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        ap_loop_exit_ready_pp0_iter23_reg <= ap_loop_exit_ready_pp0_iter22_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter26_stage0) & (ap_idle_pp0_0to25 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter24_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        ap_loop_exit_ready_pp0_iter24_reg <= ap_loop_exit_ready_pp0_iter23_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter26_stage0) & (ap_idle_pp0_0to25 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter25_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        ap_loop_exit_ready_pp0_iter25_reg <= ap_loop_exit_ready_pp0_iter24_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter26_stage0) & (ap_idle_pp0_0to25 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter26_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        ap_loop_exit_ready_pp0_iter26_reg <= ap_loop_exit_ready_pp0_iter25_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter26_stage0) & (ap_idle_pp0_0to25 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter26_stage0) & (ap_idle_pp0_0to25 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter26_stage0) & (ap_idle_pp0_0to25 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter26_stage0) & (ap_idle_pp0_0to25 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter26_stage0) & (ap_idle_pp0_0to25 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter6_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter26_stage0) & (ap_idle_pp0_0to25 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter7_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter26_stage0) & (ap_idle_pp0_0to25 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter8_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter26_stage0) & (ap_idle_pp0_0to25 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter9_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        indvar_flatten_fu_148 <= 32'd0;
    end else if (((icmp_ln75_fu_275_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        indvar_flatten_fu_148 <= add_ln75_1_fu_280_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        x_fu_144 <= 16'd0;
    end else if (((icmp_ln75_fu_275_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        x_fu_144 <= select_ln75_fu_311_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        y_fu_140 <= 16'd0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (icmp_ln75_reg_870 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0))) begin
        y_fu_140 <= add_ln78_fu_482_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0))) begin
        B_reg_962 <= B_fu_552_p1;
        add_ln86_reg_891 <= add_ln86_fu_372_p2;
        add_ln86_reg_891_pp0_iter10_reg <= add_ln86_reg_891_pp0_iter9_reg;
        add_ln86_reg_891_pp0_iter11_reg <= add_ln86_reg_891_pp0_iter10_reg;
        add_ln86_reg_891_pp0_iter12_reg <= add_ln86_reg_891_pp0_iter11_reg;
        add_ln86_reg_891_pp0_iter13_reg <= add_ln86_reg_891_pp0_iter12_reg;
        add_ln86_reg_891_pp0_iter14_reg <= add_ln86_reg_891_pp0_iter13_reg;
        add_ln86_reg_891_pp0_iter15_reg <= add_ln86_reg_891_pp0_iter14_reg;
        add_ln86_reg_891_pp0_iter16_reg <= add_ln86_reg_891_pp0_iter15_reg;
        add_ln86_reg_891_pp0_iter17_reg <= add_ln86_reg_891_pp0_iter16_reg;
        add_ln86_reg_891_pp0_iter18_reg <= add_ln86_reg_891_pp0_iter17_reg;
        add_ln86_reg_891_pp0_iter19_reg <= add_ln86_reg_891_pp0_iter18_reg;
        add_ln86_reg_891_pp0_iter1_reg <= add_ln86_reg_891;
        add_ln86_reg_891_pp0_iter20_reg <= add_ln86_reg_891_pp0_iter19_reg;
        add_ln86_reg_891_pp0_iter21_reg <= add_ln86_reg_891_pp0_iter20_reg;
        add_ln86_reg_891_pp0_iter22_reg <= add_ln86_reg_891_pp0_iter21_reg;
        add_ln86_reg_891_pp0_iter23_reg <= add_ln86_reg_891_pp0_iter22_reg;
        add_ln86_reg_891_pp0_iter24_reg <= add_ln86_reg_891_pp0_iter23_reg;
        add_ln86_reg_891_pp0_iter25_reg <= add_ln86_reg_891_pp0_iter24_reg;
        add_ln86_reg_891_pp0_iter2_reg <= add_ln86_reg_891_pp0_iter1_reg;
        add_ln86_reg_891_pp0_iter3_reg <= add_ln86_reg_891_pp0_iter2_reg;
        add_ln86_reg_891_pp0_iter4_reg <= add_ln86_reg_891_pp0_iter3_reg;
        add_ln86_reg_891_pp0_iter5_reg <= add_ln86_reg_891_pp0_iter4_reg;
        add_ln86_reg_891_pp0_iter6_reg <= add_ln86_reg_891_pp0_iter5_reg;
        add_ln86_reg_891_pp0_iter7_reg <= add_ln86_reg_891_pp0_iter6_reg;
        add_ln86_reg_891_pp0_iter8_reg <= add_ln86_reg_891_pp0_iter7_reg;
        add_ln86_reg_891_pp0_iter9_reg <= add_ln86_reg_891_pp0_iter8_reg;
        trunc_ln2_reg_1026 <= {{add_ln83_2_fu_763_p2[15:8]}};
        zext_ln83_1_reg_969[7 : 0] <= zext_ln83_1_fu_556_p1[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0))) begin
        G_reg_951 <= G_fu_532_p1;
        bit_sel_reg_1016 <= add_ln85_2_fu_700_p2[32'd15];
        part_sel_reg_1021 <= {{add_ln85_2_fu_700_p2[14:8]}};
        zext_ln86_3_reg_1010[21 : 0] <= zext_ln86_3_fu_680_p1[21 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        R_reg_934 <= R_fu_508_p1;
        R_reg_934_pp0_iter26_reg <= R_reg_934;
        add_ln83_3_reg_985 <= add_ln83_3_fu_580_p2;
        add_ln85_1_reg_1005[13 : 1] <= add_ln85_1_fu_674_p2[13 : 1];
        bit_sel1_reg_990 <= add_ln84_2_fu_619_p2[32'd15];
        part_sel1_reg_995 <= {{add_ln84_2_fu_619_p2[14:8]}};
        zext_ln83_reg_945[7 : 0] <= zext_ln83_fu_512_p1[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        add_ln86_1_reg_881[26 : 8] <= add_ln86_1_fu_343_p2[26 : 8];
        icmp_ln75_reg_870 <= icmp_ln75_fu_275_p2;
        icmp_ln75_reg_870_pp0_iter10_reg <= icmp_ln75_reg_870_pp0_iter9_reg;
        icmp_ln75_reg_870_pp0_iter11_reg <= icmp_ln75_reg_870_pp0_iter10_reg;
        icmp_ln75_reg_870_pp0_iter12_reg <= icmp_ln75_reg_870_pp0_iter11_reg;
        icmp_ln75_reg_870_pp0_iter13_reg <= icmp_ln75_reg_870_pp0_iter12_reg;
        icmp_ln75_reg_870_pp0_iter14_reg <= icmp_ln75_reg_870_pp0_iter13_reg;
        icmp_ln75_reg_870_pp0_iter15_reg <= icmp_ln75_reg_870_pp0_iter14_reg;
        icmp_ln75_reg_870_pp0_iter16_reg <= icmp_ln75_reg_870_pp0_iter15_reg;
        icmp_ln75_reg_870_pp0_iter17_reg <= icmp_ln75_reg_870_pp0_iter16_reg;
        icmp_ln75_reg_870_pp0_iter18_reg <= icmp_ln75_reg_870_pp0_iter17_reg;
        icmp_ln75_reg_870_pp0_iter19_reg <= icmp_ln75_reg_870_pp0_iter18_reg;
        icmp_ln75_reg_870_pp0_iter1_reg <= icmp_ln75_reg_870;
        icmp_ln75_reg_870_pp0_iter20_reg <= icmp_ln75_reg_870_pp0_iter19_reg;
        icmp_ln75_reg_870_pp0_iter21_reg <= icmp_ln75_reg_870_pp0_iter20_reg;
        icmp_ln75_reg_870_pp0_iter22_reg <= icmp_ln75_reg_870_pp0_iter21_reg;
        icmp_ln75_reg_870_pp0_iter23_reg <= icmp_ln75_reg_870_pp0_iter22_reg;
        icmp_ln75_reg_870_pp0_iter24_reg <= icmp_ln75_reg_870_pp0_iter23_reg;
        icmp_ln75_reg_870_pp0_iter25_reg <= icmp_ln75_reg_870_pp0_iter24_reg;
        icmp_ln75_reg_870_pp0_iter2_reg <= icmp_ln75_reg_870_pp0_iter1_reg;
        icmp_ln75_reg_870_pp0_iter3_reg <= icmp_ln75_reg_870_pp0_iter2_reg;
        icmp_ln75_reg_870_pp0_iter4_reg <= icmp_ln75_reg_870_pp0_iter3_reg;
        icmp_ln75_reg_870_pp0_iter5_reg <= icmp_ln75_reg_870_pp0_iter4_reg;
        icmp_ln75_reg_870_pp0_iter6_reg <= icmp_ln75_reg_870_pp0_iter5_reg;
        icmp_ln75_reg_870_pp0_iter7_reg <= icmp_ln75_reg_870_pp0_iter6_reg;
        icmp_ln75_reg_870_pp0_iter8_reg <= icmp_ln75_reg_870_pp0_iter7_reg;
        icmp_ln75_reg_870_pp0_iter9_reg <= icmp_ln75_reg_870_pp0_iter8_reg;
        select_ln60_reg_874 <= select_ln60_fu_303_p3;
        trunc_ln75_reg_886[21 : 8] <= trunc_ln75_fu_349_p1[21 : 8];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp5) & (1'b0 == ap_block_pp0_stage0_subdone_grp5_done_reg))) begin
        gmem_addr_3_read_reg_940 <= m_axi_gmem_0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001_grp3))) begin
        gmem_addr_3_reg_907 <= sext_ln81_fu_433_p1;
        gmem_addr_4_reg_918 <= sext_ln82_fu_468_p1;
        gmem_addr_read_reg_929 <= m_axi_gmem_0_RDATA;
        gmem_addr_reg_896 <= sext_ln80_fu_398_p1;
        trunc_ln80_reg_902 <= trunc_ln80_fu_408_p1;
        trunc_ln80_reg_902_pp0_iter10_reg <= trunc_ln80_reg_902_pp0_iter9_reg;
        trunc_ln80_reg_902_pp0_iter11_reg <= trunc_ln80_reg_902_pp0_iter10_reg;
        trunc_ln80_reg_902_pp0_iter12_reg <= trunc_ln80_reg_902_pp0_iter11_reg;
        trunc_ln80_reg_902_pp0_iter13_reg <= trunc_ln80_reg_902_pp0_iter12_reg;
        trunc_ln80_reg_902_pp0_iter14_reg <= trunc_ln80_reg_902_pp0_iter13_reg;
        trunc_ln80_reg_902_pp0_iter15_reg <= trunc_ln80_reg_902_pp0_iter14_reg;
        trunc_ln80_reg_902_pp0_iter16_reg <= trunc_ln80_reg_902_pp0_iter15_reg;
        trunc_ln80_reg_902_pp0_iter17_reg <= trunc_ln80_reg_902_pp0_iter16_reg;
        trunc_ln80_reg_902_pp0_iter18_reg <= trunc_ln80_reg_902_pp0_iter17_reg;
        trunc_ln80_reg_902_pp0_iter19_reg <= trunc_ln80_reg_902_pp0_iter18_reg;
        trunc_ln80_reg_902_pp0_iter1_reg <= trunc_ln80_reg_902;
        trunc_ln80_reg_902_pp0_iter20_reg <= trunc_ln80_reg_902_pp0_iter19_reg;
        trunc_ln80_reg_902_pp0_iter21_reg <= trunc_ln80_reg_902_pp0_iter20_reg;
        trunc_ln80_reg_902_pp0_iter22_reg <= trunc_ln80_reg_902_pp0_iter21_reg;
        trunc_ln80_reg_902_pp0_iter23_reg <= trunc_ln80_reg_902_pp0_iter22_reg;
        trunc_ln80_reg_902_pp0_iter24_reg <= trunc_ln80_reg_902_pp0_iter23_reg;
        trunc_ln80_reg_902_pp0_iter2_reg <= trunc_ln80_reg_902_pp0_iter1_reg;
        trunc_ln80_reg_902_pp0_iter3_reg <= trunc_ln80_reg_902_pp0_iter2_reg;
        trunc_ln80_reg_902_pp0_iter4_reg <= trunc_ln80_reg_902_pp0_iter3_reg;
        trunc_ln80_reg_902_pp0_iter5_reg <= trunc_ln80_reg_902_pp0_iter4_reg;
        trunc_ln80_reg_902_pp0_iter6_reg <= trunc_ln80_reg_902_pp0_iter5_reg;
        trunc_ln80_reg_902_pp0_iter7_reg <= trunc_ln80_reg_902_pp0_iter6_reg;
        trunc_ln80_reg_902_pp0_iter8_reg <= trunc_ln80_reg_902_pp0_iter7_reg;
        trunc_ln80_reg_902_pp0_iter9_reg <= trunc_ln80_reg_902_pp0_iter8_reg;
        trunc_ln81_reg_913 <= trunc_ln81_fu_443_p1;
        trunc_ln81_reg_913_pp0_iter10_reg <= trunc_ln81_reg_913_pp0_iter9_reg;
        trunc_ln81_reg_913_pp0_iter11_reg <= trunc_ln81_reg_913_pp0_iter10_reg;
        trunc_ln81_reg_913_pp0_iter12_reg <= trunc_ln81_reg_913_pp0_iter11_reg;
        trunc_ln81_reg_913_pp0_iter13_reg <= trunc_ln81_reg_913_pp0_iter12_reg;
        trunc_ln81_reg_913_pp0_iter14_reg <= trunc_ln81_reg_913_pp0_iter13_reg;
        trunc_ln81_reg_913_pp0_iter15_reg <= trunc_ln81_reg_913_pp0_iter14_reg;
        trunc_ln81_reg_913_pp0_iter16_reg <= trunc_ln81_reg_913_pp0_iter15_reg;
        trunc_ln81_reg_913_pp0_iter17_reg <= trunc_ln81_reg_913_pp0_iter16_reg;
        trunc_ln81_reg_913_pp0_iter18_reg <= trunc_ln81_reg_913_pp0_iter17_reg;
        trunc_ln81_reg_913_pp0_iter19_reg <= trunc_ln81_reg_913_pp0_iter18_reg;
        trunc_ln81_reg_913_pp0_iter1_reg <= trunc_ln81_reg_913;
        trunc_ln81_reg_913_pp0_iter20_reg <= trunc_ln81_reg_913_pp0_iter19_reg;
        trunc_ln81_reg_913_pp0_iter21_reg <= trunc_ln81_reg_913_pp0_iter20_reg;
        trunc_ln81_reg_913_pp0_iter22_reg <= trunc_ln81_reg_913_pp0_iter21_reg;
        trunc_ln81_reg_913_pp0_iter23_reg <= trunc_ln81_reg_913_pp0_iter22_reg;
        trunc_ln81_reg_913_pp0_iter24_reg <= trunc_ln81_reg_913_pp0_iter23_reg;
        trunc_ln81_reg_913_pp0_iter2_reg <= trunc_ln81_reg_913_pp0_iter1_reg;
        trunc_ln81_reg_913_pp0_iter3_reg <= trunc_ln81_reg_913_pp0_iter2_reg;
        trunc_ln81_reg_913_pp0_iter4_reg <= trunc_ln81_reg_913_pp0_iter3_reg;
        trunc_ln81_reg_913_pp0_iter5_reg <= trunc_ln81_reg_913_pp0_iter4_reg;
        trunc_ln81_reg_913_pp0_iter6_reg <= trunc_ln81_reg_913_pp0_iter5_reg;
        trunc_ln81_reg_913_pp0_iter7_reg <= trunc_ln81_reg_913_pp0_iter6_reg;
        trunc_ln81_reg_913_pp0_iter8_reg <= trunc_ln81_reg_913_pp0_iter7_reg;
        trunc_ln81_reg_913_pp0_iter9_reg <= trunc_ln81_reg_913_pp0_iter8_reg;
        trunc_ln82_reg_924 <= trunc_ln82_fu_478_p1;
        trunc_ln82_reg_924_pp0_iter10_reg <= trunc_ln82_reg_924_pp0_iter9_reg;
        trunc_ln82_reg_924_pp0_iter11_reg <= trunc_ln82_reg_924_pp0_iter10_reg;
        trunc_ln82_reg_924_pp0_iter12_reg <= trunc_ln82_reg_924_pp0_iter11_reg;
        trunc_ln82_reg_924_pp0_iter13_reg <= trunc_ln82_reg_924_pp0_iter12_reg;
        trunc_ln82_reg_924_pp0_iter14_reg <= trunc_ln82_reg_924_pp0_iter13_reg;
        trunc_ln82_reg_924_pp0_iter15_reg <= trunc_ln82_reg_924_pp0_iter14_reg;
        trunc_ln82_reg_924_pp0_iter16_reg <= trunc_ln82_reg_924_pp0_iter15_reg;
        trunc_ln82_reg_924_pp0_iter17_reg <= trunc_ln82_reg_924_pp0_iter16_reg;
        trunc_ln82_reg_924_pp0_iter18_reg <= trunc_ln82_reg_924_pp0_iter17_reg;
        trunc_ln82_reg_924_pp0_iter19_reg <= trunc_ln82_reg_924_pp0_iter18_reg;
        trunc_ln82_reg_924_pp0_iter1_reg <= trunc_ln82_reg_924;
        trunc_ln82_reg_924_pp0_iter20_reg <= trunc_ln82_reg_924_pp0_iter19_reg;
        trunc_ln82_reg_924_pp0_iter21_reg <= trunc_ln82_reg_924_pp0_iter20_reg;
        trunc_ln82_reg_924_pp0_iter22_reg <= trunc_ln82_reg_924_pp0_iter21_reg;
        trunc_ln82_reg_924_pp0_iter23_reg <= trunc_ln82_reg_924_pp0_iter22_reg;
        trunc_ln82_reg_924_pp0_iter24_reg <= trunc_ln82_reg_924_pp0_iter23_reg;
        trunc_ln82_reg_924_pp0_iter2_reg <= trunc_ln82_reg_924_pp0_iter1_reg;
        trunc_ln82_reg_924_pp0_iter3_reg <= trunc_ln82_reg_924_pp0_iter2_reg;
        trunc_ln82_reg_924_pp0_iter4_reg <= trunc_ln82_reg_924_pp0_iter3_reg;
        trunc_ln82_reg_924_pp0_iter5_reg <= trunc_ln82_reg_924_pp0_iter4_reg;
        trunc_ln82_reg_924_pp0_iter6_reg <= trunc_ln82_reg_924_pp0_iter5_reg;
        trunc_ln82_reg_924_pp0_iter7_reg <= trunc_ln82_reg_924_pp0_iter6_reg;
        trunc_ln82_reg_924_pp0_iter8_reg <= trunc_ln82_reg_924_pp0_iter7_reg;
        trunc_ln82_reg_924_pp0_iter9_reg <= trunc_ln82_reg_924_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp6) & (1'b0 == ap_block_pp0_stage1_subdone_grp6_done_reg))) begin
        gmem_addr_4_read_reg_957 <= m_axi_gmem_0_RDATA;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (icmp_ln75_reg_870 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter26 == 1'b1) & (icmp_ln75_reg_870_pp0_iter25_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter26_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter26_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter26_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (~((ap_loop_exit_ready == 1'b0) & (ap_loop_exit_ready_pp0_iter26_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter25_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter24_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter23_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter22_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter21_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter20_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter19_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter18_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter17_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter16_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter15_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter14_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter13_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter12_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter11_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter10_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter9_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter8_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter7_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter5_reg 
    == 1'b0) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b0))) begin
        ap_done_pending_pp0 = 1'b1;
    end else begin
        ap_done_pending_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter26 == 1'b0) & (ap_enable_reg_pp0_iter25 == 1'b0) & (ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter27 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter25 == 1'b0) & (ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to25 = 1'b1;
    end else begin
        ap_idle_pp0_0to25 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter26 == 1'b0) & (ap_enable_reg_pp0_iter25 == 1'b0) & (ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter27 == 1'b0))) begin
        ap_idle_pp0_1to27 = 1'b1;
    end else begin
        ap_idle_pp0_1to27 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg) & (1'b0 == ap_block_pp0_stage1_grp2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln75_reg_870 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_grp1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_grp3)))) begin
        gmem_blk_n_AR = m_axi_gmem_0_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter25 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp6_done_reg) & (1'b0 == ap_block_pp0_stage1_grp6)) | ((ap_enable_reg_pp0_iter25 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp5_done_reg) & (1'b0 == ap_block_pp0_stage0_grp5)) | ((ap_enable_reg_pp0_iter24 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_grp3)))) begin
        gmem_blk_n_R = m_axi_gmem_0_RVALID;
    end else begin
        gmem_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0)) | ((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0)))) begin
        grp_fu_798_ce = 1'b1;
    end else begin
        grp_fu_798_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0)) | ((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0)))) begin
        grp_fu_807_ce = 1'b1;
    end else begin
        grp_fu_807_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0)) | ((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0)))) begin
        grp_fu_815_ce = 1'b1;
    end else begin
        grp_fu_815_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001_grp3))) begin
            m_axi_gmem_0_ARADDR = gmem_addr_4_reg_918;
        end else if ((1'b1 == ap_condition_1274)) begin
            m_axi_gmem_0_ARADDR = gmem_addr_3_reg_907;
        end else if ((1'b1 == ap_condition_1270)) begin
            m_axi_gmem_0_ARADDR = gmem_addr_reg_896;
        end else begin
            m_axi_gmem_0_ARADDR = 'bx;
        end
    end else begin
        m_axi_gmem_0_ARADDR = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp2) & (1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln75_reg_870 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001_grp3)))) begin
        m_axi_gmem_0_ARVALID = 1'b1;
    end else begin
        m_axi_gmem_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter25 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp6) & (1'b0 == ap_block_pp0_stage1_subdone_grp6_done_reg)) | ((ap_enable_reg_pp0_iter25 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp5) & (1'b0 == ap_block_pp0_stage0_subdone_grp5_done_reg)) | ((ap_enable_reg_pp0_iter24 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001_grp3)))) begin
        m_axi_gmem_0_RREADY = 1'b1;
    end else begin
        m_axi_gmem_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter27 == 1'b1))) begin
        p_yuv_channels_ch1_ce0_local = 1'b1;
    end else begin
        p_yuv_channels_ch1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter27 == 1'b1))) begin
        p_yuv_channels_ch1_we0_local = 1'b1;
    end else begin
        p_yuv_channels_ch1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter26 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0))) begin
        p_yuv_channels_ch2_ce0_local = 1'b1;
    end else begin
        p_yuv_channels_ch2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter26 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0))) begin
        p_yuv_channels_ch2_we0_local = 1'b1;
    end else begin
        p_yuv_channels_ch2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter26 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0))) begin
        p_yuv_channels_ch3_ce0_local = 1'b1;
    end else begin
        p_yuv_channels_ch3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter26 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0))) begin
        p_yuv_channels_ch3_we0_local = 1'b1;
    end else begin
        p_yuv_channels_ch3_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((1'b1 == ap_condition_exit_pp0_iter26_stage0) & (ap_idle_pp0_0to25 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_done_pending_pp0 == 1'b0) & (ap_idle_pp0_1to27 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign B_fu_552_p1 = lshr_ln82_fu_547_p2[7:0];

assign G_fu_532_p1 = lshr_ln81_fu_527_p2[7:0];

assign R_fu_508_p1 = lshr_ln80_fu_503_p2[7:0];

assign U_fu_689_p3 = {{xor_ln84_fu_684_p2}, {part_sel1_reg_995}};

assign V_fu_784_p3 = {{xor_ln85_fu_779_p2}, {part_sel_reg_1021}};

assign Y_fu_792_p2 = (trunc_ln2_reg_1026 + 8'd16);

assign add_ln75_1_fu_280_p2 = (indvar_flatten_fu_148 + 32'd1);

assign add_ln75_fu_292_p2 = (x_fu_144 + 16'd1);

assign add_ln78_fu_482_p2 = (select_ln60_reg_874 + 16'd1);

assign add_ln80_1_fu_377_p2 = (zext_ln78_1_fu_366_p1 + in_channels_ch1);

assign add_ln80_fu_382_p2 = (add_ln80_1_fu_377_p2 + zext_ln78_fu_363_p1);

assign add_ln81_1_fu_412_p2 = (zext_ln78_1_fu_366_p1 + in_channels_ch2);

assign add_ln81_fu_417_p2 = (add_ln81_1_fu_412_p2 + zext_ln78_fu_363_p1);

assign add_ln82_1_fu_447_p2 = (zext_ln78_1_fu_366_p1 + in_channels_ch3);

assign add_ln82_fu_452_p2 = (add_ln82_1_fu_447_p2 + zext_ln78_fu_363_p1);

assign add_ln83_2_fu_763_p2 = (zext_ln83_6_fu_760_p1 + add_ln83_fu_755_p2);

assign add_ln83_3_fu_580_p2 = (zext_ln83_3_fu_576_p1 + zext_ln83_1_reg_969);

assign add_ln83_4_fu_745_p2 = (zext_ln83_4_fu_730_p1 + zext_ln83_7_fu_741_p1);

assign add_ln83_fu_755_p2 = (zext_ln83_5_fu_751_p1 + add_ln83_3_reg_985);

assign add_ln84_1_fu_609_p2 = (sub_ln84_fu_603_p2 + 15'd128);

assign add_ln84_2_fu_619_p2 = ($signed(zext_ln84_fu_615_p1) + $signed(grp_fu_798_p3));

assign add_ln85_1_fu_674_p2 = (sub_ln85_1_fu_668_p2 + 14'd128);

assign add_ln85_2_fu_700_p2 = ($signed(sext_ln85_fu_697_p1) + $signed(grp_fu_807_p3));

assign add_ln86_1_fu_343_p2 = (zext_ln86_fu_327_p1 + zext_ln86_1_fu_339_p1);

assign add_ln86_fu_372_p2 = (trunc_ln75_reg_886 + zext_ln86_2_fu_369_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter25 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp5_done_reg) & (m_axi_gmem_0_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state4_io_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg)));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state4_io_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp5 = ((ap_enable_reg_pp0_iter25 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp5_done_reg) & (m_axi_gmem_0_RVALID == 1'b0));
end

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter25 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp5_done_reg) & (m_axi_gmem_0_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state4_io_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg)));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp1 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state4_io_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp5 = ((ap_enable_reg_pp0_iter25 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp5_done_reg) & (m_axi_gmem_0_RVALID == 1'b0));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001 = (((ap_enable_reg_pp0_iter25 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp6_done_reg) & (m_axi_gmem_0_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg) & (m_axi_gmem_0_ARREADY == 1'b0)));
end

assign ap_block_pp0_stage1_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001_grp2 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg) & (m_axi_gmem_0_ARREADY == 1'b0));
end

always @ (*) begin
    ap_block_pp0_stage1_11001_grp6 = ((ap_enable_reg_pp0_iter25 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp6_done_reg) & (m_axi_gmem_0_RVALID == 1'b0));
end

assign ap_block_pp0_stage1_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_grp2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_grp6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = (((ap_enable_reg_pp0_iter25 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp6_done_reg) & (m_axi_gmem_0_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg) & (m_axi_gmem_0_ARREADY == 1'b0)));
end

assign ap_block_pp0_stage1_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone_grp2 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg) & (m_axi_gmem_0_ARREADY == 1'b0));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone_grp6 = ((ap_enable_reg_pp0_iter25 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp6_done_reg) & (m_axi_gmem_0_RVALID == 1'b0));
end

always @ (*) begin
    ap_block_pp0_stage2_11001 = (((ap_enable_reg_pp0_iter24 == 1'b1) & (m_axi_gmem_0_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (m_axi_gmem_0_ARREADY == 1'b0)));
end

assign ap_block_pp0_stage2_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_11001_grp3 = (((ap_enable_reg_pp0_iter24 == 1'b1) & (m_axi_gmem_0_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (m_axi_gmem_0_ARREADY == 1'b0)));
end

assign ap_block_pp0_stage2_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_grp3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_subdone = (((ap_enable_reg_pp0_iter24 == 1'b1) & (m_axi_gmem_0_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (m_axi_gmem_0_ARREADY == 1'b0)));
end

assign ap_block_pp0_stage2_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_io_grp1 = ((icmp_ln75_reg_870 == 1'd0) & (m_axi_gmem_0_ARREADY == 1'b0));
end

always @ (*) begin
    ap_condition_1270 = ((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln75_reg_870 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg));
end

always @ (*) begin
    ap_condition_1274 = ((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp2) & (1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage2;

assign ap_ready = ap_ready_sig;

assign grp_fu_798_p0 = grp_fu_798_p00;

assign grp_fu_798_p00 = R_fu_508_p1;

assign grp_fu_798_p1 = 15'd32730;

assign grp_fu_807_p0 = zext_ln83_reg_945;

assign grp_fu_807_p1 = 15'd122;

assign grp_fu_815_p0 = grp_fu_815_p00;

assign grp_fu_815_p00 = B_fu_552_p1;

assign grp_fu_815_p1 = 13'd25;

assign grp_fu_815_p2 = 13'd128;

assign icmp_ln75_fu_275_p2 = ((indvar_flatten_fu_148 == mul_ln30) ? 1'b1 : 1'b0);

assign icmp_ln78_fu_298_p2 = ((y_fu_140 == height) ? 1'b1 : 1'b0);

assign lshr_ln80_fu_503_p2 = gmem_addr_read_reg_929 >> zext_ln80_fu_499_p1;

assign lshr_ln81_fu_527_p2 = gmem_addr_3_read_reg_940 >> zext_ln81_fu_523_p1;

assign lshr_ln82_fu_547_p2 = gmem_addr_4_read_reg_957 >> zext_ln82_fu_543_p1;

assign m_axi_gmem_0_ARBURST = 2'd0;

assign m_axi_gmem_0_ARCACHE = 4'd0;

assign m_axi_gmem_0_ARID = 1'd0;

assign m_axi_gmem_0_ARLEN = 64'd1;

assign m_axi_gmem_0_ARLOCK = 2'd0;

assign m_axi_gmem_0_ARPROT = 3'd0;

assign m_axi_gmem_0_ARQOS = 4'd0;

assign m_axi_gmem_0_ARREGION = 4'd0;

assign m_axi_gmem_0_ARSIZE = 3'd0;

assign m_axi_gmem_0_ARUSER = 1'd0;

assign m_axi_gmem_0_AWADDR = 64'd0;

assign m_axi_gmem_0_AWBURST = 2'd0;

assign m_axi_gmem_0_AWCACHE = 4'd0;

assign m_axi_gmem_0_AWID = 1'd0;

assign m_axi_gmem_0_AWLEN = 32'd0;

assign m_axi_gmem_0_AWLOCK = 2'd0;

assign m_axi_gmem_0_AWPROT = 3'd0;

assign m_axi_gmem_0_AWQOS = 4'd0;

assign m_axi_gmem_0_AWREGION = 4'd0;

assign m_axi_gmem_0_AWSIZE = 3'd0;

assign m_axi_gmem_0_AWUSER = 1'd0;

assign m_axi_gmem_0_AWVALID = 1'b0;

assign m_axi_gmem_0_BREADY = 1'b0;

assign m_axi_gmem_0_WDATA = 16'd0;

assign m_axi_gmem_0_WID = 1'd0;

assign m_axi_gmem_0_WLAST = 1'b0;

assign m_axi_gmem_0_WSTRB = 2'd0;

assign m_axi_gmem_0_WUSER = 1'd0;

assign m_axi_gmem_0_WVALID = 1'b0;

assign mul_ln84_fu_563_p0 = mul_ln84_fu_563_p00;

assign mul_ln84_fu_563_p00 = G_reg_951;

assign mul_ln84_fu_563_p1 = 16'd65462;

assign mul_ln85_fu_642_p0 = zext_ln83_1_reg_969;

assign mul_ln85_fu_642_p1 = 16'd65442;

assign p_shl2_fu_585_p3 = {{B_reg_962}, {7'd0}};

assign p_yuv_channels_ch1_address0 = zext_ln86_3_reg_1010;

assign p_yuv_channels_ch1_ce0 = p_yuv_channels_ch1_ce0_local;

assign p_yuv_channels_ch1_d0 = Y_fu_792_p2;

assign p_yuv_channels_ch1_we0 = p_yuv_channels_ch1_we0_local;

assign p_yuv_channels_ch2_address0 = zext_ln86_3_fu_680_p1;

assign p_yuv_channels_ch2_ce0 = p_yuv_channels_ch2_ce0_local;

assign p_yuv_channels_ch2_d0 = U_fu_689_p3;

assign p_yuv_channels_ch2_we0 = p_yuv_channels_ch2_we0_local;

assign p_yuv_channels_ch3_address0 = zext_ln86_3_reg_1010;

assign p_yuv_channels_ch3_ce0 = p_yuv_channels_ch3_ce0_local;

assign p_yuv_channels_ch3_d0 = V_fu_784_p3;

assign p_yuv_channels_ch3_we0 = p_yuv_channels_ch3_we0_local;

assign select_ln60_fu_303_p3 = ((icmp_ln78_fu_298_p2[0:0] == 1'b1) ? 16'd0 : y_fu_140);

assign select_ln75_fu_311_p3 = ((icmp_ln78_fu_298_p2[0:0] == 1'b1) ? add_ln75_fu_292_p2 : x_fu_144);

assign sext_ln80_fu_398_p1 = $signed(trunc_ln80_1_fu_388_p4);

assign sext_ln81_fu_433_p1 = $signed(trunc_ln81_1_fu_423_p4);

assign sext_ln82_fu_468_p1 = $signed(trunc_ln82_1_fu_458_p4);

assign sext_ln85_fu_697_p1 = $signed(add_ln85_1_reg_1005);

assign shl_ln1_fu_516_p3 = {{trunc_ln81_reg_913_pp0_iter24_reg}, {3'd0}};

assign shl_ln2_fu_536_p3 = {{trunc_ln82_reg_924_pp0_iter24_reg}, {3'd0}};

assign shl_ln_fu_492_p3 = {{trunc_ln80_reg_902_pp0_iter24_reg}, {3'd0}};

assign sub_ln84_fu_603_p2 = (p_shl2_fu_585_p3 - zext_ln84_1_fu_599_p1);

assign sub_ln85_1_fu_668_p2 = (sub_ln85_fu_651_p2 - zext_ln85_2_fu_664_p1);

assign sub_ln85_fu_651_p2 = (14'd0 - zext_ln85_1_fu_647_p1);

assign tmp_10_fu_331_p3 = {{select_ln75_fu_311_p3}, {8'd0}};

assign tmp_11_fu_569_p3 = {{G_reg_951}, {7'd0}};

assign tmp_12_fu_723_p3 = {{R_reg_934_pp0_iter26_reg}, {6'd0}};

assign tmp_13_fu_734_p3 = {{R_reg_934_pp0_iter26_reg}, {1'd0}};

assign tmp_14_fu_592_p3 = {{B_reg_962}, {4'd0}};

assign tmp_15_fu_657_p3 = {{B_reg_962}, {1'd0}};

assign tmp_fu_319_p3 = {{select_ln75_fu_311_p3}, {10'd0}};

assign trunc_ln75_fu_349_p1 = add_ln86_1_fu_343_p2[21:0];

assign trunc_ln80_1_fu_388_p4 = {{add_ln80_fu_382_p2[63:1]}};

assign trunc_ln80_fu_408_p1 = add_ln80_fu_382_p2[0:0];

assign trunc_ln81_1_fu_423_p4 = {{add_ln81_fu_417_p2[63:1]}};

assign trunc_ln81_fu_443_p1 = add_ln81_fu_417_p2[0:0];

assign trunc_ln82_1_fu_458_p4 = {{add_ln82_fu_452_p2[63:1]}};

assign trunc_ln82_fu_478_p1 = add_ln82_fu_452_p2[0:0];

assign xor_ln84_fu_684_p2 = (bit_sel1_reg_990 ^ 1'd1);

assign xor_ln85_fu_779_p2 = (bit_sel_reg_1016 ^ 1'd1);

assign zext_ln78_1_fu_366_p1 = select_ln60_reg_874;

assign zext_ln78_fu_363_p1 = add_ln86_1_reg_881;

assign zext_ln80_fu_499_p1 = shl_ln_fu_492_p3;

assign zext_ln81_fu_523_p1 = shl_ln1_fu_516_p3;

assign zext_ln82_fu_543_p1 = shl_ln2_fu_536_p3;

assign zext_ln83_1_fu_556_p1 = G_reg_951;

assign zext_ln83_3_fu_576_p1 = tmp_11_fu_569_p3;

assign zext_ln83_4_fu_730_p1 = tmp_12_fu_723_p3;

assign zext_ln83_5_fu_751_p1 = add_ln83_4_fu_745_p2;

assign zext_ln83_6_fu_760_p1 = grp_fu_815_p3;

assign zext_ln83_7_fu_741_p1 = tmp_13_fu_734_p3;

assign zext_ln83_fu_512_p1 = R_fu_508_p1;

assign zext_ln84_1_fu_599_p1 = tmp_14_fu_592_p3;

assign zext_ln84_fu_615_p1 = add_ln84_1_fu_609_p2;

assign zext_ln85_1_fu_647_p1 = tmp_14_fu_592_p3;

assign zext_ln85_2_fu_664_p1 = tmp_15_fu_657_p3;

assign zext_ln86_1_fu_339_p1 = tmp_10_fu_331_p3;

assign zext_ln86_2_fu_369_p1 = select_ln60_reg_874;

assign zext_ln86_3_fu_680_p1 = add_ln86_reg_891_pp0_iter25_reg;

assign zext_ln86_fu_327_p1 = tmp_fu_319_p3;

always @ (posedge ap_clk) begin
    add_ln86_1_reg_881[7:0] <= 8'b00000000;
    trunc_ln75_reg_886[7:0] <= 8'b00000000;
    zext_ln83_reg_945[14:8] <= 7'b0000000;
    zext_ln83_1_reg_969[15:8] <= 8'b00000000;
    add_ln85_1_reg_1005[0] <= 1'b0;
    zext_ln86_3_reg_1010[63:22] <= 42'b000000000000000000000000000000000000000000;
end

endmodule //yuv_filter_yuv_filter_Pipeline_RGB2YUV_LOOP_X_RGB2YUV_LOOP_Y
