-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dct_Loop_Xpose_Col_Outer_Loop_proc is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    col_outbuf_i_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    col_outbuf_i_ce0 : OUT STD_LOGIC;
    col_outbuf_i_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    buf_2d_out_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    buf_2d_out_ce0 : OUT STD_LOGIC;
    buf_2d_out_we0 : OUT STD_LOGIC;
    buf_2d_out_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of dct_Loop_Xpose_Col_Outer_Loop_proc is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv6_3F : STD_LOGIC_VECTOR (5 downto 0) := "111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln80_fu_181_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_condition_exit_pp0_iter0_stage0_pp0_iter1_reg : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_loop_exit_ready_delayed : STD_LOGIC;
    signal select_ln57_fu_121_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln57_reg_248 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln57_reg_248_pp0_iter1_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln80_1_fu_141_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln80_1_reg_253 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln80_1_reg_253_pp0_iter1_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln86_fu_157_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln86_reg_258 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln83_fu_175_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln83_reg_263 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln80_reg_268 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_icmp_ln834_phi_fu_84_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln86_2_fu_202_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln86_3_fu_222_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal indvar_flatten1_fu_42 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal add_ln80_1_fu_169_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_sig_allocacmp_indvar_flatten1_load : STD_LOGIC_VECTOR (5 downto 0);
    signal j2_fu_46 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal j_fu_133_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_j2_load : STD_LOGIC_VECTOR (3 downto 0);
    signal i3_fu_50 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal i_fu_163_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_i3_load : STD_LOGIC_VECTOR (3 downto 0);
    signal col_outbuf_i_ce0_local : STD_LOGIC;
    signal buf_2d_out_we0_local : STD_LOGIC;
    signal buf_2d_out_ce0_local : STD_LOGIC;
    signal add_ln80_fu_115_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln80_fu_129_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_4_fu_149_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln86_fu_145_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_206_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln86_1_fu_213_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln86_1_fu_216_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_244 : BOOLEAN;
    signal ap_condition_90 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component dct_flow_control_loop_delay_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_loop_exit_ready_delayed : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_delay_pipe_U : component dct_flow_control_loop_delay_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_continue,
        ap_loop_exit_ready_delayed => ap_loop_exit_ready_delayed);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter2_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_0))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
            end if; 
        end if;
    end process;

    i3_fu_50_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_90)) then
                i3_fu_50 <= i_fu_163_p2;
            end if;
        end if;
    end process;

    indvar_flatten1_fu_42_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_90)) then
                indvar_flatten1_fu_42 <= add_ln80_1_fu_169_p2;
            end if;
        end if;
    end process;

    j2_fu_46_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_90)) then
                j2_fu_46 <= j_fu_133_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln86_reg_258 <= add_ln86_fu_157_p2;
                ap_condition_exit_pp0_iter0_stage0_pp0_iter1_reg <= ap_condition_exit_pp0_iter0_stage0;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                icmp_ln80_reg_268 <= icmp_ln80_fu_181_p2;
                select_ln57_reg_248 <= select_ln57_fu_121_p3;
                select_ln57_reg_248_pp0_iter1_reg <= select_ln57_reg_248;
                trunc_ln80_1_reg_253 <= trunc_ln80_1_fu_141_p1;
                trunc_ln80_1_reg_253_pp0_iter1_reg <= trunc_ln80_1_reg_253;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln83_reg_263 <= icmp_ln83_fu_175_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln80_1_fu_169_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten1_load) + unsigned(ap_const_lv6_1));
    add_ln80_fu_115_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_j2_load) + unsigned(ap_const_lv4_1));
    add_ln86_1_fu_216_p2 <= std_logic_vector(unsigned(tmp_fu_206_p3) + unsigned(zext_ln86_1_fu_213_p1));
    add_ln86_fu_157_p2 <= std_logic_vector(unsigned(tmp_4_fu_149_p3) + unsigned(zext_ln86_fu_145_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_start_int)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_start_int)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_done_reg = ap_const_logic_1);
    end process;


    ap_condition_244_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln80_reg_268, ap_block_pp0_stage0)
    begin
                ap_condition_244 <= ((icmp_ln80_reg_268 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_condition_90_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
                ap_condition_90 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, icmp_ln80_fu_181_p2, ap_start_int)
    begin
        if (((icmp_ln80_fu_181_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_done_reg, ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_loop_exit_ready_delayed_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_condition_exit_pp0_iter0_stage0_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0_pp0_iter1_reg) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_loop_exit_ready_delayed <= ap_const_logic_1;
        else 
            ap_loop_exit_ready_delayed <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_icmp_ln834_phi_fu_84_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln83_reg_263, ap_loop_init, ap_condition_244)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
            if ((ap_const_boolean_1 = ap_condition_244)) then 
                ap_phi_mux_icmp_ln834_phi_fu_84_p4 <= icmp_ln83_reg_263;
            elsif ((ap_loop_init = ap_const_logic_1)) then 
                ap_phi_mux_icmp_ln834_phi_fu_84_p4 <= ap_const_lv1_0;
            else 
                ap_phi_mux_icmp_ln834_phi_fu_84_p4 <= icmp_ln83_reg_263;
            end if;
        else 
            ap_phi_mux_icmp_ln834_phi_fu_84_p4 <= icmp_ln83_reg_263;
        end if; 
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i3_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, ap_block_pp0_stage0, i3_fu_50, ap_start_int)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i3_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_i3_load <= i3_fu_50;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten1_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, ap_block_pp0_stage0, indvar_flatten1_fu_42, ap_start_int)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten1_load <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_indvar_flatten1_load <= indvar_flatten1_fu_42;
        end if; 
    end process;


    ap_sig_allocacmp_j2_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, ap_block_pp0_stage0, j2_fu_46, ap_start_int)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_j2_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_j2_load <= j2_fu_46;
        end if; 
    end process;

    buf_2d_out_address0 <= zext_ln86_3_fu_222_p1(6 - 1 downto 0);
    buf_2d_out_ce0 <= buf_2d_out_ce0_local;

    buf_2d_out_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            buf_2d_out_ce0_local <= ap_const_logic_1;
        else 
            buf_2d_out_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    buf_2d_out_d0 <= col_outbuf_i_q0;
    buf_2d_out_we0 <= buf_2d_out_we0_local;

    buf_2d_out_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            buf_2d_out_we0_local <= ap_const_logic_1;
        else 
            buf_2d_out_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    col_outbuf_i_address0 <= zext_ln86_2_fu_202_p1(6 - 1 downto 0);
    col_outbuf_i_ce0 <= col_outbuf_i_ce0_local;

    col_outbuf_i_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            col_outbuf_i_ce0_local <= ap_const_logic_1;
        else 
            col_outbuf_i_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    i_fu_163_p2 <= std_logic_vector(unsigned(select_ln57_fu_121_p3) + unsigned(ap_const_lv4_1));
    icmp_ln80_fu_181_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten1_load = ap_const_lv6_3F) else "0";
    icmp_ln83_fu_175_p2 <= "1" when (i_fu_163_p2 = ap_const_lv4_8) else "0";
    j_fu_133_p3 <= 
        add_ln80_fu_115_p2 when (ap_phi_mux_icmp_ln834_phi_fu_84_p4(0) = '1') else 
        ap_sig_allocacmp_j2_load;
    select_ln57_fu_121_p3 <= 
        ap_const_lv4_0 when (ap_phi_mux_icmp_ln834_phi_fu_84_p4(0) = '1') else 
        ap_sig_allocacmp_i3_load;
    tmp_4_fu_149_p3 <= (trunc_ln80_fu_129_p1 & ap_const_lv3_0);
    tmp_fu_206_p3 <= (trunc_ln80_1_reg_253_pp0_iter1_reg & ap_const_lv3_0);
    trunc_ln80_1_fu_141_p1 <= j_fu_133_p3(3 - 1 downto 0);
    trunc_ln80_fu_129_p1 <= select_ln57_fu_121_p3(3 - 1 downto 0);
    zext_ln86_1_fu_213_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln57_reg_248_pp0_iter1_reg),6));
    zext_ln86_2_fu_202_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln86_reg_258),64));
    zext_ln86_3_fu_222_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln86_1_fu_216_p2),64));
    zext_ln86_fu_145_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_fu_133_p3),6));
end behav;
