// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module dct_Loop_Col_DCT_Loop_proc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        col_inbuf_i_0_address0,
        col_inbuf_i_0_ce0,
        col_inbuf_i_0_q0,
        col_inbuf_i_1_address0,
        col_inbuf_i_1_ce0,
        col_inbuf_i_1_q0,
        col_inbuf_i_2_address0,
        col_inbuf_i_2_ce0,
        col_inbuf_i_2_q0,
        col_inbuf_i_3_address0,
        col_inbuf_i_3_ce0,
        col_inbuf_i_3_q0,
        col_inbuf_i_4_address0,
        col_inbuf_i_4_ce0,
        col_inbuf_i_4_q0,
        col_inbuf_i_5_address0,
        col_inbuf_i_5_ce0,
        col_inbuf_i_5_q0,
        col_inbuf_i_6_address0,
        col_inbuf_i_6_ce0,
        col_inbuf_i_6_q0,
        col_inbuf_i_7_address0,
        col_inbuf_i_7_ce0,
        col_inbuf_i_7_q0,
        col_outbuf_i_address0,
        col_outbuf_i_ce0,
        col_outbuf_i_we0,
        col_outbuf_i_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [2:0] col_inbuf_i_0_address0;
output   col_inbuf_i_0_ce0;
input  [15:0] col_inbuf_i_0_q0;
output  [2:0] col_inbuf_i_1_address0;
output   col_inbuf_i_1_ce0;
input  [15:0] col_inbuf_i_1_q0;
output  [2:0] col_inbuf_i_2_address0;
output   col_inbuf_i_2_ce0;
input  [15:0] col_inbuf_i_2_q0;
output  [2:0] col_inbuf_i_3_address0;
output   col_inbuf_i_3_ce0;
input  [15:0] col_inbuf_i_3_q0;
output  [2:0] col_inbuf_i_4_address0;
output   col_inbuf_i_4_ce0;
input  [15:0] col_inbuf_i_4_q0;
output  [2:0] col_inbuf_i_5_address0;
output   col_inbuf_i_5_ce0;
input  [15:0] col_inbuf_i_5_q0;
output  [2:0] col_inbuf_i_6_address0;
output   col_inbuf_i_6_ce0;
input  [15:0] col_inbuf_i_6_q0;
output  [2:0] col_inbuf_i_7_address0;
output   col_inbuf_i_7_ce0;
input  [15:0] col_inbuf_i_7_q0;
output  [5:0] col_outbuf_i_address0;
output   col_outbuf_i_ce0;
output   col_outbuf_i_we0;
output  [15:0] col_outbuf_i_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_idle_pp0;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln75_fu_415_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [2:0] dct_1d_dct_coeff_table_0_address0;
wire   [13:0] dct_1d_dct_coeff_table_0_q0;
wire   [2:0] dct_1d_dct_coeff_table_1_address0;
wire  signed [14:0] dct_1d_dct_coeff_table_1_q0;
wire   [2:0] dct_1d_dct_coeff_table_2_address0;
wire   [14:0] dct_1d_dct_coeff_table_2_q0;
wire   [2:0] dct_1d_dct_coeff_table_3_address0;
wire  signed [14:0] dct_1d_dct_coeff_table_3_q0;
wire   [2:0] dct_1d_dct_coeff_table_4_address0;
wire   [14:0] dct_1d_dct_coeff_table_4_q0;
wire   [2:0] dct_1d_dct_coeff_table_5_address0;
wire  signed [14:0] dct_1d_dct_coeff_table_5_q0;
wire   [2:0] dct_1d_dct_coeff_table_6_address0;
wire   [14:0] dct_1d_dct_coeff_table_6_q0;
wire   [2:0] dct_1d_dct_coeff_table_7_address0;
wire  signed [14:0] dct_1d_dct_coeff_table_7_q0;
wire   [3:0] select_ln57_fu_353_p3;
reg   [3:0] select_ln57_reg_613;
reg    ap_block_pp0_stage0_11001;
reg   [3:0] select_ln57_reg_613_pp0_iter1_reg;
reg   [3:0] select_ln57_reg_613_pp0_iter2_reg;
reg   [3:0] select_ln57_reg_613_pp0_iter3_reg;
reg   [3:0] select_ln57_reg_613_pp0_iter4_reg;
reg   [3:0] select_ln57_reg_613_pp0_iter5_reg;
reg   [3:0] select_ln57_reg_613_pp0_iter6_reg;
wire   [2:0] trunc_ln75_fu_369_p1;
reg   [2:0] trunc_ln75_reg_618;
reg   [2:0] trunc_ln75_reg_618_pp0_iter1_reg;
reg   [2:0] trunc_ln75_reg_618_pp0_iter2_reg;
reg   [2:0] trunc_ln75_reg_618_pp0_iter3_reg;
reg   [2:0] trunc_ln75_reg_618_pp0_iter4_reg;
reg   [2:0] trunc_ln75_reg_618_pp0_iter5_reg;
reg   [2:0] trunc_ln75_reg_618_pp0_iter6_reg;
wire   [0:0] icmp_ln39_fu_409_p2;
reg   [0:0] icmp_ln39_reg_703;
reg   [0:0] icmp_ln75_reg_708;
reg  signed [15:0] col_inbuf_i_0_load_reg_712;
reg  signed [15:0] col_inbuf_i_2_load_reg_717;
reg  signed [15:0] col_inbuf_i_4_load_reg_722;
reg  signed [15:0] col_inbuf_i_6_load_reg_727;
reg   [13:0] coeff_reg_752;
reg  signed [14:0] coeff_9_reg_762;
reg  signed [14:0] coeff_11_reg_772;
reg  signed [14:0] coeff_13_reg_782;
wire   [28:0] mul_ln46_9_fu_492_p2;
reg  signed [28:0] mul_ln46_9_reg_802;
wire   [28:0] mul_ln46_11_fu_498_p2;
reg  signed [28:0] mul_ln46_11_reg_807;
wire   [28:0] mul_ln46_13_fu_504_p2;
reg  signed [28:0] mul_ln46_13_reg_812;
wire  signed [28:0] grp_fu_554_p3;
reg  signed [28:0] add_ln46_reg_817;
reg  signed [28:0] add_ln46_reg_817_pp0_iter5_reg;
wire  signed [28:0] grp_fu_569_p3;
reg  signed [28:0] add_ln46_8_reg_822;
reg  signed [28:0] add_ln46_8_reg_822_pp0_iter5_reg;
wire  signed [28:0] grp_fu_576_p3;
reg  signed [28:0] add_ln46_10_reg_827;
wire   [28:0] grp_fu_561_p3;
(* use_dsp48 = "no" *) wire   [28:0] add_ln46_13_fu_510_p2;
reg   [28:0] add_ln46_13_reg_837;
reg   [15:0] trunc_ln_reg_842;
reg   [0:0] ap_phi_mux_icmp_ln394_phi_fu_316_p4;
wire    ap_loop_init;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln75_fu_373_p1;
wire   [63:0] zext_ln39_fu_385_p1;
wire   [63:0] zext_ln46_4_fu_549_p1;
reg   [5:0] indvar_flatten1_fu_80;
wire   [5:0] add_ln75_1_fu_403_p2;
reg   [5:0] ap_sig_allocacmp_indvar_flatten1_load;
reg   [3:0] i2_fu_84;
wire   [3:0] i_fu_361_p3;
reg   [3:0] ap_sig_allocacmp_i2_load;
reg   [3:0] k3_fu_88;
wire   [3:0] k_fu_397_p2;
reg   [3:0] ap_sig_allocacmp_k3_load;
reg    col_inbuf_i_0_ce0_local;
reg    col_inbuf_i_1_ce0_local;
reg    col_inbuf_i_2_ce0_local;
reg    col_inbuf_i_3_ce0_local;
reg    col_inbuf_i_4_ce0_local;
reg    col_inbuf_i_5_ce0_local;
reg    col_inbuf_i_6_ce0_local;
reg    col_inbuf_i_7_ce0_local;
reg    dct_1d_dct_coeff_table_0_ce0_local;
reg    dct_1d_dct_coeff_table_1_ce0_local;
reg    dct_1d_dct_coeff_table_2_ce0_local;
reg    dct_1d_dct_coeff_table_3_ce0_local;
reg    dct_1d_dct_coeff_table_4_ce0_local;
reg    dct_1d_dct_coeff_table_5_ce0_local;
reg    dct_1d_dct_coeff_table_6_ce0_local;
reg    dct_1d_dct_coeff_table_7_ce0_local;
reg    col_outbuf_i_we0_local;
reg    col_outbuf_i_ce0_local;
wire   [3:0] add_ln75_fu_347_p2;
wire   [13:0] mul_ln46_9_fu_492_p1;
wire  signed [28:0] add_ln46_13_fu_510_p0;
wire   [28:0] grp_fu_583_p3;
(* use_dsp48 = "no" *) wire   [28:0] add_ln46_9_fu_514_p2;
wire   [28:0] add_ln46_14_fu_518_p2;
wire   [5:0] tmp_fu_533_p3;
wire   [5:0] zext_ln46_3_fu_540_p1;
wire   [5:0] add_ln46_15_fu_543_p2;
wire   [12:0] grp_fu_561_p2;
reg    grp_fu_554_ce;
reg    grp_fu_561_ce;
reg    grp_fu_569_ce;
reg    grp_fu_576_ce;
reg    grp_fu_583_ce;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [28:0] mul_ln46_9_fu_492_p10;
reg    ap_condition_645;
reg    ap_condition_238;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 indvar_flatten1_fu_80 = 6'd0;
#0 i2_fu_84 = 4'd0;
#0 k3_fu_88 = 4'd0;
end

dct_Loop_Row_DCT_Loop_proc_dct_1d_dct_coeff_table_02_ROM_AUTO_1R #(
    .DataWidth( 14 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
dct_1d_dct_coeff_table_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dct_1d_dct_coeff_table_0_address0),
    .ce0(dct_1d_dct_coeff_table_0_ce0_local),
    .q0(dct_1d_dct_coeff_table_0_q0)
);

dct_Loop_Row_DCT_Loop_proc_dct_1d_dct_coeff_table_13_ROM_AUTO_1R #(
    .DataWidth( 15 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
dct_1d_dct_coeff_table_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dct_1d_dct_coeff_table_1_address0),
    .ce0(dct_1d_dct_coeff_table_1_ce0_local),
    .q0(dct_1d_dct_coeff_table_1_q0)
);

dct_Loop_Row_DCT_Loop_proc_dct_1d_dct_coeff_table_24_ROM_AUTO_1R #(
    .DataWidth( 15 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
dct_1d_dct_coeff_table_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dct_1d_dct_coeff_table_2_address0),
    .ce0(dct_1d_dct_coeff_table_2_ce0_local),
    .q0(dct_1d_dct_coeff_table_2_q0)
);

dct_Loop_Row_DCT_Loop_proc_dct_1d_dct_coeff_table_35_ROM_AUTO_1R #(
    .DataWidth( 15 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
dct_1d_dct_coeff_table_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dct_1d_dct_coeff_table_3_address0),
    .ce0(dct_1d_dct_coeff_table_3_ce0_local),
    .q0(dct_1d_dct_coeff_table_3_q0)
);

dct_Loop_Row_DCT_Loop_proc_dct_1d_dct_coeff_table_46_ROM_AUTO_1R #(
    .DataWidth( 15 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
dct_1d_dct_coeff_table_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dct_1d_dct_coeff_table_4_address0),
    .ce0(dct_1d_dct_coeff_table_4_ce0_local),
    .q0(dct_1d_dct_coeff_table_4_q0)
);

dct_Loop_Row_DCT_Loop_proc_dct_1d_dct_coeff_table_57_ROM_AUTO_1R #(
    .DataWidth( 15 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
dct_1d_dct_coeff_table_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dct_1d_dct_coeff_table_5_address0),
    .ce0(dct_1d_dct_coeff_table_5_ce0_local),
    .q0(dct_1d_dct_coeff_table_5_q0)
);

dct_Loop_Row_DCT_Loop_proc_dct_1d_dct_coeff_table_68_ROM_AUTO_1R #(
    .DataWidth( 15 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
dct_1d_dct_coeff_table_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dct_1d_dct_coeff_table_6_address0),
    .ce0(dct_1d_dct_coeff_table_6_ce0_local),
    .q0(dct_1d_dct_coeff_table_6_q0)
);

dct_Loop_Row_DCT_Loop_proc_dct_1d_dct_coeff_table_79_ROM_AUTO_1R #(
    .DataWidth( 15 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
dct_1d_dct_coeff_table_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dct_1d_dct_coeff_table_7_address0),
    .ce0(dct_1d_dct_coeff_table_7_ce0_local),
    .q0(dct_1d_dct_coeff_table_7_q0)
);

dct_mul_16s_14ns_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 29 ))
mul_16s_14ns_29_1_1_U49(
    .din0(col_inbuf_i_0_load_reg_712),
    .din1(mul_ln46_9_fu_492_p1),
    .dout(mul_ln46_9_fu_492_p2)
);

dct_mul_16s_15s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 29 ))
mul_16s_15s_29_1_1_U50(
    .din0(col_inbuf_i_4_load_reg_722),
    .din1(coeff_11_reg_772),
    .dout(mul_ln46_11_fu_498_p2)
);

dct_mul_16s_15s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 29 ))
mul_16s_15s_29_1_1_U51(
    .din0(col_inbuf_i_2_load_reg_717),
    .din1(coeff_9_reg_762),
    .dout(mul_ln46_13_fu_504_p2)
);

dct_mac_muladd_16s_15s_29s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_15s_29s_29_4_1_U52(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(col_inbuf_i_1_q0),
    .din1(dct_1d_dct_coeff_table_1_q0),
    .din2(mul_ln46_9_reg_802),
    .ce(grp_fu_554_ce),
    .dout(grp_fu_554_p3)
);

dct_mac_muladd_16s_15s_13ns_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 13 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_15s_13ns_29_4_1_U53(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(col_inbuf_i_7_q0),
    .din1(dct_1d_dct_coeff_table_7_q0),
    .din2(grp_fu_561_p2),
    .ce(grp_fu_561_ce),
    .dout(grp_fu_561_p3)
);

dct_mac_muladd_16s_15s_29s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_15s_29s_29_4_1_U54(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(col_inbuf_i_3_q0),
    .din1(dct_1d_dct_coeff_table_3_q0),
    .din2(mul_ln46_13_reg_812),
    .ce(grp_fu_569_ce),
    .dout(grp_fu_569_p3)
);

dct_mac_muladd_16s_15s_29s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_15s_29s_29_4_1_U55(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(col_inbuf_i_5_q0),
    .din1(dct_1d_dct_coeff_table_5_q0),
    .din2(mul_ln46_11_reg_807),
    .ce(grp_fu_576_ce),
    .dout(grp_fu_576_p3)
);

dct_mac_muladd_16s_15s_29ns_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_15s_29ns_29_4_1_U56(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(col_inbuf_i_6_load_reg_727),
    .din1(coeff_13_reg_782),
    .din2(grp_fu_561_p3),
    .ce(grp_fu_583_ce),
    .dout(grp_fu_583_p3)
);

dct_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter7_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_loop_exit_ready_pp0_iter7_reg <= 1'b0;
    end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_238)) begin
        i2_fu_84 <= i_fu_361_p3;
    end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_238)) begin
    indvar_flatten1_fu_80 <= add_ln75_1_fu_403_p2;
end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_238)) begin
    k3_fu_88 <= k_fu_397_p2;
end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        add_ln46_10_reg_827 <= grp_fu_576_p3;
        add_ln46_8_reg_822 <= grp_fu_569_p3;
        add_ln46_reg_817 <= grp_fu_554_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln46_13_reg_837 <= add_ln46_13_fu_510_p2;
        add_ln46_8_reg_822_pp0_iter5_reg <= add_ln46_8_reg_822;
        add_ln46_reg_817_pp0_iter5_reg <= add_ln46_reg_817;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        mul_ln46_11_reg_807 <= mul_ln46_11_fu_498_p2;
        mul_ln46_13_reg_812 <= mul_ln46_13_fu_504_p2;
        mul_ln46_9_reg_802 <= mul_ln46_9_fu_492_p2;
        select_ln57_reg_613_pp0_iter2_reg <= select_ln57_reg_613_pp0_iter1_reg;
        select_ln57_reg_613_pp0_iter3_reg <= select_ln57_reg_613_pp0_iter2_reg;
        select_ln57_reg_613_pp0_iter4_reg <= select_ln57_reg_613_pp0_iter3_reg;
        select_ln57_reg_613_pp0_iter5_reg <= select_ln57_reg_613_pp0_iter4_reg;
        select_ln57_reg_613_pp0_iter6_reg <= select_ln57_reg_613_pp0_iter5_reg;
        trunc_ln75_reg_618_pp0_iter2_reg <= trunc_ln75_reg_618_pp0_iter1_reg;
        trunc_ln75_reg_618_pp0_iter3_reg <= trunc_ln75_reg_618_pp0_iter2_reg;
        trunc_ln75_reg_618_pp0_iter4_reg <= trunc_ln75_reg_618_pp0_iter3_reg;
        trunc_ln75_reg_618_pp0_iter5_reg <= trunc_ln75_reg_618_pp0_iter4_reg;
        trunc_ln75_reg_618_pp0_iter6_reg <= trunc_ln75_reg_618_pp0_iter5_reg;
        trunc_ln_reg_842 <= {{add_ln46_14_fu_518_p2[28:13]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        coeff_11_reg_772 <= dct_1d_dct_coeff_table_4_q0;
        coeff_13_reg_782 <= dct_1d_dct_coeff_table_6_q0;
        coeff_9_reg_762 <= dct_1d_dct_coeff_table_2_q0;
        coeff_reg_752 <= dct_1d_dct_coeff_table_0_q0;
        col_inbuf_i_0_load_reg_712 <= col_inbuf_i_0_q0;
        col_inbuf_i_2_load_reg_717 <= col_inbuf_i_2_q0;
        col_inbuf_i_4_load_reg_722 <= col_inbuf_i_4_q0;
        col_inbuf_i_6_load_reg_727 <= col_inbuf_i_6_q0;
        icmp_ln75_reg_708 <= icmp_ln75_fu_415_p2;
        select_ln57_reg_613 <= select_ln57_fu_353_p3;
        select_ln57_reg_613_pp0_iter1_reg <= select_ln57_reg_613;
        trunc_ln75_reg_618 <= trunc_ln75_fu_369_p1;
        trunc_ln75_reg_618_pp0_iter1_reg <= trunc_ln75_reg_618;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln39_reg_703 <= icmp_ln39_fu_409_p2;
    end
end

always @ (*) begin
    if (((icmp_ln75_fu_415_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter7_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_645)) begin
            ap_phi_mux_icmp_ln394_phi_fu_316_p4 = icmp_ln39_reg_703;
        end else if ((ap_loop_init == 1'b1)) begin
            ap_phi_mux_icmp_ln394_phi_fu_316_p4 = 1'd0;
        end else begin
            ap_phi_mux_icmp_ln394_phi_fu_316_p4 = icmp_ln39_reg_703;
        end
    end else begin
        ap_phi_mux_icmp_ln394_phi_fu_316_p4 = icmp_ln39_reg_703;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i2_load = 4'd0;
    end else begin
        ap_sig_allocacmp_i2_load = i2_fu_84;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten1_load = 6'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten1_load = indvar_flatten1_fu_80;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_k3_load = 4'd0;
    end else begin
        ap_sig_allocacmp_k3_load = k3_fu_88;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        col_inbuf_i_0_ce0_local = 1'b1;
    end else begin
        col_inbuf_i_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        col_inbuf_i_1_ce0_local = 1'b1;
    end else begin
        col_inbuf_i_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        col_inbuf_i_2_ce0_local = 1'b1;
    end else begin
        col_inbuf_i_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        col_inbuf_i_3_ce0_local = 1'b1;
    end else begin
        col_inbuf_i_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        col_inbuf_i_4_ce0_local = 1'b1;
    end else begin
        col_inbuf_i_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        col_inbuf_i_5_ce0_local = 1'b1;
    end else begin
        col_inbuf_i_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        col_inbuf_i_6_ce0_local = 1'b1;
    end else begin
        col_inbuf_i_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        col_inbuf_i_7_ce0_local = 1'b1;
    end else begin
        col_inbuf_i_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        col_outbuf_i_ce0_local = 1'b1;
    end else begin
        col_outbuf_i_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        col_outbuf_i_we0_local = 1'b1;
    end else begin
        col_outbuf_i_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dct_1d_dct_coeff_table_0_ce0_local = 1'b1;
    end else begin
        dct_1d_dct_coeff_table_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dct_1d_dct_coeff_table_1_ce0_local = 1'b1;
    end else begin
        dct_1d_dct_coeff_table_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dct_1d_dct_coeff_table_2_ce0_local = 1'b1;
    end else begin
        dct_1d_dct_coeff_table_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dct_1d_dct_coeff_table_3_ce0_local = 1'b1;
    end else begin
        dct_1d_dct_coeff_table_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dct_1d_dct_coeff_table_4_ce0_local = 1'b1;
    end else begin
        dct_1d_dct_coeff_table_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dct_1d_dct_coeff_table_5_ce0_local = 1'b1;
    end else begin
        dct_1d_dct_coeff_table_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dct_1d_dct_coeff_table_6_ce0_local = 1'b1;
    end else begin
        dct_1d_dct_coeff_table_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dct_1d_dct_coeff_table_7_ce0_local = 1'b1;
    end else begin
        dct_1d_dct_coeff_table_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_554_ce = 1'b1;
    end else begin
        grp_fu_554_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_561_ce = 1'b1;
    end else begin
        grp_fu_561_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_569_ce = 1'b1;
    end else begin
        grp_fu_569_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_576_ce = 1'b1;
    end else begin
        grp_fu_576_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        grp_fu_583_ce = 1'b1;
    end else begin
        grp_fu_583_ce = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln46_13_fu_510_p0 = grp_fu_583_p3;

assign add_ln46_13_fu_510_p2 = ($signed(add_ln46_13_fu_510_p0) + $signed(add_ln46_10_reg_827));

assign add_ln46_14_fu_518_p2 = (add_ln46_13_reg_837 + add_ln46_9_fu_514_p2);

assign add_ln46_15_fu_543_p2 = (tmp_fu_533_p3 + zext_ln46_3_fu_540_p1);

assign add_ln46_9_fu_514_p2 = ($signed(add_ln46_8_reg_822_pp0_iter5_reg) + $signed(add_ln46_reg_817_pp0_iter5_reg));

assign add_ln75_1_fu_403_p2 = (ap_sig_allocacmp_indvar_flatten1_load + 6'd1);

assign add_ln75_fu_347_p2 = (ap_sig_allocacmp_i2_load + 4'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_condition_238 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_645 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln75_reg_708 == 1'd0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign col_inbuf_i_0_address0 = zext_ln75_fu_373_p1;

assign col_inbuf_i_0_ce0 = col_inbuf_i_0_ce0_local;

assign col_inbuf_i_1_address0 = zext_ln75_fu_373_p1;

assign col_inbuf_i_1_ce0 = col_inbuf_i_1_ce0_local;

assign col_inbuf_i_2_address0 = zext_ln75_fu_373_p1;

assign col_inbuf_i_2_ce0 = col_inbuf_i_2_ce0_local;

assign col_inbuf_i_3_address0 = zext_ln75_fu_373_p1;

assign col_inbuf_i_3_ce0 = col_inbuf_i_3_ce0_local;

assign col_inbuf_i_4_address0 = zext_ln75_fu_373_p1;

assign col_inbuf_i_4_ce0 = col_inbuf_i_4_ce0_local;

assign col_inbuf_i_5_address0 = zext_ln75_fu_373_p1;

assign col_inbuf_i_5_ce0 = col_inbuf_i_5_ce0_local;

assign col_inbuf_i_6_address0 = zext_ln75_fu_373_p1;

assign col_inbuf_i_6_ce0 = col_inbuf_i_6_ce0_local;

assign col_inbuf_i_7_address0 = zext_ln75_fu_373_p1;

assign col_inbuf_i_7_ce0 = col_inbuf_i_7_ce0_local;

assign col_outbuf_i_address0 = zext_ln46_4_fu_549_p1;

assign col_outbuf_i_ce0 = col_outbuf_i_ce0_local;

assign col_outbuf_i_d0 = trunc_ln_reg_842;

assign col_outbuf_i_we0 = col_outbuf_i_we0_local;

assign dct_1d_dct_coeff_table_0_address0 = zext_ln39_fu_385_p1;

assign dct_1d_dct_coeff_table_1_address0 = zext_ln39_fu_385_p1;

assign dct_1d_dct_coeff_table_2_address0 = zext_ln39_fu_385_p1;

assign dct_1d_dct_coeff_table_3_address0 = zext_ln39_fu_385_p1;

assign dct_1d_dct_coeff_table_4_address0 = zext_ln39_fu_385_p1;

assign dct_1d_dct_coeff_table_5_address0 = zext_ln39_fu_385_p1;

assign dct_1d_dct_coeff_table_6_address0 = zext_ln39_fu_385_p1;

assign dct_1d_dct_coeff_table_7_address0 = zext_ln39_fu_385_p1;

assign grp_fu_561_p2 = 29'd4096;

assign i_fu_361_p3 = ((ap_phi_mux_icmp_ln394_phi_fu_316_p4[0:0] == 1'b1) ? add_ln75_fu_347_p2 : ap_sig_allocacmp_i2_load);

assign icmp_ln39_fu_409_p2 = ((k_fu_397_p2 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln75_fu_415_p2 = ((ap_sig_allocacmp_indvar_flatten1_load == 6'd63) ? 1'b1 : 1'b0);

assign k_fu_397_p2 = (select_ln57_fu_353_p3 + 4'd1);

assign mul_ln46_9_fu_492_p1 = mul_ln46_9_fu_492_p10;

assign mul_ln46_9_fu_492_p10 = coeff_reg_752;

assign select_ln57_fu_353_p3 = ((ap_phi_mux_icmp_ln394_phi_fu_316_p4[0:0] == 1'b1) ? 4'd0 : ap_sig_allocacmp_k3_load);

assign tmp_fu_533_p3 = {{trunc_ln75_reg_618_pp0_iter6_reg}, {3'd0}};

assign trunc_ln75_fu_369_p1 = i_fu_361_p3[2:0];

assign zext_ln39_fu_385_p1 = select_ln57_fu_353_p3;

assign zext_ln46_3_fu_540_p1 = select_ln57_reg_613_pp0_iter6_reg;

assign zext_ln46_4_fu_549_p1 = add_ln46_15_fu_543_p2;

assign zext_ln75_fu_373_p1 = i_fu_361_p3;

endmodule //dct_Loop_Col_DCT_Loop_proc
