-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dct_read_data is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_r_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    input_r_ce0 : OUT STD_LOGIC;
    input_r_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    buf_0_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    buf_0_ce0 : OUT STD_LOGIC;
    buf_0_we0 : OUT STD_LOGIC;
    buf_0_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    buf_1_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    buf_1_ce0 : OUT STD_LOGIC;
    buf_1_we0 : OUT STD_LOGIC;
    buf_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    buf_2_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    buf_2_ce0 : OUT STD_LOGIC;
    buf_2_we0 : OUT STD_LOGIC;
    buf_2_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    buf_3_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    buf_3_ce0 : OUT STD_LOGIC;
    buf_3_we0 : OUT STD_LOGIC;
    buf_3_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    buf_4_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    buf_4_ce0 : OUT STD_LOGIC;
    buf_4_we0 : OUT STD_LOGIC;
    buf_4_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    buf_5_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    buf_5_ce0 : OUT STD_LOGIC;
    buf_5_we0 : OUT STD_LOGIC;
    buf_5_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    buf_6_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    buf_6_ce0 : OUT STD_LOGIC;
    buf_6_we0 : OUT STD_LOGIC;
    buf_6_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    buf_7_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    buf_7_ce0 : OUT STD_LOGIC;
    buf_7_we0 : OUT STD_LOGIC;
    buf_7_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of dct_read_data is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv6_3F : STD_LOGIC_VECTOR (5 downto 0) := "111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln94_fu_291_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_condition_exit_pp0_iter0_stage0_pp0_iter1_reg : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_loop_exit_ready_delayed : STD_LOGIC;
    signal select_ln91_fu_249_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln91_reg_365 : STD_LOGIC_VECTOR (3 downto 0);
    signal r_fu_257_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal r_reg_370 : STD_LOGIC_VECTOR (3 downto 0);
    signal r_reg_370_pp0_iter1_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal empty_fu_265_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal empty_reg_375 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln96_fu_269_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln96_reg_380 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln96_reg_380_pp0_iter1_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln96_fu_285_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln96_reg_384 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln94_reg_389 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_icmp_ln965_phi_fu_212_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln99_fu_328_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln94_fu_333_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal indvar_flatten2_fu_72 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal add_ln94_1_fu_273_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_sig_allocacmp_indvar_flatten2_load : STD_LOGIC_VECTOR (5 downto 0);
    signal r3_fu_76 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal ap_sig_allocacmp_r3_load : STD_LOGIC_VECTOR (3 downto 0);
    signal c4_fu_80 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal c_fu_279_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_c4_load : STD_LOGIC_VECTOR (3 downto 0);
    signal input_r_ce0_local : STD_LOGIC;
    signal buf_6_we0_local : STD_LOGIC;
    signal buf_6_ce0_local : STD_LOGIC;
    signal buf_5_we0_local : STD_LOGIC;
    signal buf_5_ce0_local : STD_LOGIC;
    signal buf_4_we0_local : STD_LOGIC;
    signal buf_4_ce0_local : STD_LOGIC;
    signal buf_3_we0_local : STD_LOGIC;
    signal buf_3_ce0_local : STD_LOGIC;
    signal buf_2_we0_local : STD_LOGIC;
    signal buf_2_ce0_local : STD_LOGIC;
    signal buf_1_we0_local : STD_LOGIC;
    signal buf_1_ce0_local : STD_LOGIC;
    signal buf_0_we0_local : STD_LOGIC;
    signal buf_0_ce0_local : STD_LOGIC;
    signal buf_7_we0_local : STD_LOGIC;
    signal buf_7_ce0_local : STD_LOGIC;
    signal add_ln94_fu_243_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_3_fu_312_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln96_fu_319_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln99_fu_322_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_369 : BOOLEAN;
    signal ap_condition_141 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component dct_flow_control_loop_delay_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_loop_exit_ready_delayed : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_delay_pipe_U : component dct_flow_control_loop_delay_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_continue,
        ap_loop_exit_ready_delayed => ap_loop_exit_ready_delayed);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter2_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_0))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
            end if; 
        end if;
    end process;

    c4_fu_80_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_141)) then
                c4_fu_80 <= c_fu_279_p2;
            end if;
        end if;
    end process;

    indvar_flatten2_fu_72_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_141)) then
                indvar_flatten2_fu_72 <= add_ln94_1_fu_273_p2;
            end if;
        end if;
    end process;

    r3_fu_76_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_141)) then
                r3_fu_76 <= r_fu_257_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_condition_exit_pp0_iter0_stage0_pp0_iter1_reg <= ap_condition_exit_pp0_iter0_stage0;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                empty_reg_375 <= empty_fu_265_p1;
                icmp_ln94_reg_389 <= icmp_ln94_fu_291_p2;
                r_reg_370 <= r_fu_257_p3;
                r_reg_370_pp0_iter1_reg <= r_reg_370;
                select_ln91_reg_365 <= select_ln91_fu_249_p3;
                trunc_ln96_reg_380 <= trunc_ln96_fu_269_p1;
                trunc_ln96_reg_380_pp0_iter1_reg <= trunc_ln96_reg_380;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln96_reg_384 <= icmp_ln96_fu_285_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln94_1_fu_273_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten2_load) + unsigned(ap_const_lv6_1));
    add_ln94_fu_243_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_r3_load) + unsigned(ap_const_lv4_1));
    add_ln99_fu_322_p2 <= std_logic_vector(unsigned(tmp_3_fu_312_p3) + unsigned(zext_ln96_fu_319_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_start_int)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_start_int)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_done_reg = ap_const_logic_1);
    end process;


    ap_condition_141_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
                ap_condition_141 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_369_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln94_reg_389, ap_block_pp0_stage0)
    begin
                ap_condition_369 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln94_reg_389 = ap_const_lv1_0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, icmp_ln94_fu_291_p2, ap_start_int)
    begin
        if (((icmp_ln94_fu_291_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_done_reg, ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_loop_exit_ready_delayed_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_condition_exit_pp0_iter0_stage0_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0_pp0_iter1_reg) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_loop_exit_ready_delayed <= ap_const_logic_1;
        else 
            ap_loop_exit_ready_delayed <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_icmp_ln965_phi_fu_212_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln96_reg_384, ap_loop_init, ap_condition_369)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
            if ((ap_const_boolean_1 = ap_condition_369)) then 
                ap_phi_mux_icmp_ln965_phi_fu_212_p4 <= icmp_ln96_reg_384;
            elsif ((ap_loop_init = ap_const_logic_1)) then 
                ap_phi_mux_icmp_ln965_phi_fu_212_p4 <= ap_const_lv1_0;
            else 
                ap_phi_mux_icmp_ln965_phi_fu_212_p4 <= icmp_ln96_reg_384;
            end if;
        else 
            ap_phi_mux_icmp_ln965_phi_fu_212_p4 <= icmp_ln96_reg_384;
        end if; 
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_c4_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, ap_block_pp0_stage0, c4_fu_80, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_c4_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_c4_load <= c4_fu_80;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten2_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, ap_block_pp0_stage0, indvar_flatten2_fu_72, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten2_load <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_indvar_flatten2_load <= indvar_flatten2_fu_72;
        end if; 
    end process;


    ap_sig_allocacmp_r3_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, ap_block_pp0_stage0, r3_fu_76, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_r3_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_r3_load <= r3_fu_76;
        end if; 
    end process;

    buf_0_address0 <= zext_ln94_fu_333_p1(3 - 1 downto 0);
    buf_0_ce0 <= buf_0_ce0_local;

    buf_0_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            buf_0_ce0_local <= ap_const_logic_1;
        else 
            buf_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    buf_0_d0 <= input_r_q0;
    buf_0_we0 <= buf_0_we0_local;

    buf_0_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln96_reg_380_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln96_reg_380_pp0_iter1_reg = ap_const_lv3_0))) then 
            buf_0_we0_local <= ap_const_logic_1;
        else 
            buf_0_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    buf_1_address0 <= zext_ln94_fu_333_p1(3 - 1 downto 0);
    buf_1_ce0 <= buf_1_ce0_local;

    buf_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            buf_1_ce0_local <= ap_const_logic_1;
        else 
            buf_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    buf_1_d0 <= input_r_q0;
    buf_1_we0 <= buf_1_we0_local;

    buf_1_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln96_reg_380_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln96_reg_380_pp0_iter1_reg = ap_const_lv3_1))) then 
            buf_1_we0_local <= ap_const_logic_1;
        else 
            buf_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    buf_2_address0 <= zext_ln94_fu_333_p1(3 - 1 downto 0);
    buf_2_ce0 <= buf_2_ce0_local;

    buf_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            buf_2_ce0_local <= ap_const_logic_1;
        else 
            buf_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    buf_2_d0 <= input_r_q0;
    buf_2_we0 <= buf_2_we0_local;

    buf_2_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln96_reg_380_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln96_reg_380_pp0_iter1_reg = ap_const_lv3_2))) then 
            buf_2_we0_local <= ap_const_logic_1;
        else 
            buf_2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    buf_3_address0 <= zext_ln94_fu_333_p1(3 - 1 downto 0);
    buf_3_ce0 <= buf_3_ce0_local;

    buf_3_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            buf_3_ce0_local <= ap_const_logic_1;
        else 
            buf_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    buf_3_d0 <= input_r_q0;
    buf_3_we0 <= buf_3_we0_local;

    buf_3_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln96_reg_380_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln96_reg_380_pp0_iter1_reg = ap_const_lv3_3))) then 
            buf_3_we0_local <= ap_const_logic_1;
        else 
            buf_3_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    buf_4_address0 <= zext_ln94_fu_333_p1(3 - 1 downto 0);
    buf_4_ce0 <= buf_4_ce0_local;

    buf_4_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            buf_4_ce0_local <= ap_const_logic_1;
        else 
            buf_4_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    buf_4_d0 <= input_r_q0;
    buf_4_we0 <= buf_4_we0_local;

    buf_4_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln96_reg_380_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln96_reg_380_pp0_iter1_reg = ap_const_lv3_4))) then 
            buf_4_we0_local <= ap_const_logic_1;
        else 
            buf_4_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    buf_5_address0 <= zext_ln94_fu_333_p1(3 - 1 downto 0);
    buf_5_ce0 <= buf_5_ce0_local;

    buf_5_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            buf_5_ce0_local <= ap_const_logic_1;
        else 
            buf_5_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    buf_5_d0 <= input_r_q0;
    buf_5_we0 <= buf_5_we0_local;

    buf_5_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln96_reg_380_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln96_reg_380_pp0_iter1_reg = ap_const_lv3_5))) then 
            buf_5_we0_local <= ap_const_logic_1;
        else 
            buf_5_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    buf_6_address0 <= zext_ln94_fu_333_p1(3 - 1 downto 0);
    buf_6_ce0 <= buf_6_ce0_local;

    buf_6_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            buf_6_ce0_local <= ap_const_logic_1;
        else 
            buf_6_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    buf_6_d0 <= input_r_q0;
    buf_6_we0 <= buf_6_we0_local;

    buf_6_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln96_reg_380_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln96_reg_380_pp0_iter1_reg = ap_const_lv3_6))) then 
            buf_6_we0_local <= ap_const_logic_1;
        else 
            buf_6_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    buf_7_address0 <= zext_ln94_fu_333_p1(3 - 1 downto 0);
    buf_7_ce0 <= buf_7_ce0_local;

    buf_7_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            buf_7_ce0_local <= ap_const_logic_1;
        else 
            buf_7_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    buf_7_d0 <= input_r_q0;
    buf_7_we0 <= buf_7_we0_local;

    buf_7_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln96_reg_380_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln96_reg_380_pp0_iter1_reg = ap_const_lv3_7))) then 
            buf_7_we0_local <= ap_const_logic_1;
        else 
            buf_7_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    c_fu_279_p2 <= std_logic_vector(unsigned(select_ln91_fu_249_p3) + unsigned(ap_const_lv4_1));
    empty_fu_265_p1 <= r_fu_257_p3(3 - 1 downto 0);
    icmp_ln94_fu_291_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten2_load = ap_const_lv6_3F) else "0";
    icmp_ln96_fu_285_p2 <= "1" when (c_fu_279_p2 = ap_const_lv4_8) else "0";
    input_r_address0 <= zext_ln99_fu_328_p1(6 - 1 downto 0);
    input_r_ce0 <= input_r_ce0_local;

    input_r_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_r_ce0_local <= ap_const_logic_1;
        else 
            input_r_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    r_fu_257_p3 <= 
        add_ln94_fu_243_p2 when (ap_phi_mux_icmp_ln965_phi_fu_212_p4(0) = '1') else 
        ap_sig_allocacmp_r3_load;
    select_ln91_fu_249_p3 <= 
        ap_const_lv4_0 when (ap_phi_mux_icmp_ln965_phi_fu_212_p4(0) = '1') else 
        ap_sig_allocacmp_c4_load;
    tmp_3_fu_312_p3 <= (empty_reg_375 & ap_const_lv3_0);
    trunc_ln96_fu_269_p1 <= select_ln91_fu_249_p3(3 - 1 downto 0);
    zext_ln94_fu_333_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_reg_370_pp0_iter1_reg),64));
    zext_ln96_fu_319_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln91_reg_365),6));
    zext_ln99_fu_328_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln99_fu_322_p2),64));
end behav;
