domain_path: e:\robot\project\xilinx_fpga_class\hls\lab4_test\platform\bug_test\export\bug_test\sw\standalone_ps7_cortexa9_0
app_src_dir: E:\vitis\Vitis\2024.2\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
