domain_path: e:\robot\project\xilinx_fpga_class\hls\lab4\platform\audio\export\audio\sw\standalone_ps7_cortexa9_0
app_src_dir: E:\vitis\Vitis\2024.2\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
